fn workspace_root() -> Result<std::path::PathBuf, Box<dyn std::error::Error>> {
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR")?;
    let mut dir = std::path::Path::new(&manifest_dir).to_path_buf();
    loop {
        let cargo_toml = dir.join("Cargo.toml");
        if cargo_toml.exists() {
            if let Ok(content) = std::fs::read_to_string(&cargo_toml) {
                if content.contains("[workspace]") {
                    return Ok(dir);
                }
            }
        }
        dir = match dir.parent() {
            Some(p) => p.to_path_buf(),
            None => return Err("workspace root not found".into()),
        };
    }
}

/// Convert PascalCase RPC name to SCREAMING_SNAKE_CASE for constant names.
/// Rules:
///   - Insert `_` before an uppercase letter that follows a lowercase letter
///   - Insert `_` before a digit that follows an alphabetic character
///
/// Examples: Logout→LOGOUT, SendLoginCode→SEND_LOGIN_CODE, Enable2FA→ENABLE_2FA
fn pascal_to_screaming_snake(name: &str) -> String {
    let mut out = String::new();
    let chars: Vec<char> = name.chars().collect();
    for (i, &c) in chars.iter().enumerate() {
        if i > 0 {
            let prev = chars[i - 1];
            if (c.is_uppercase() && prev.is_lowercase())
                || (c.is_ascii_digit() && prev.is_alphabetic())
            {
                out.push('_');
            }
        }
        out.push(c.to_ascii_uppercase());
    }
    out
}

/// Parse http/v1/auth.proto and generate src/generated/http_routes.rs with
/// one `pub const {RPC}_PATH: &str = "..."` per endpoint.
/// Paths are extracted from `option (google.api.http) = { post: "..." }` annotations.
fn generate_http_routes(
    proto_path: &std::path::Path,
    generated_dir: &std::path::Path,
) -> Result<(), Box<dyn std::error::Error>> {
    let content = std::fs::read_to_string(proto_path)?;
    let mut routes: Vec<(String, String, String)> = Vec::new(); // (rpc, method, path)
    let mut current_rpc: Option<String> = None;

    for line in content.lines() {
        let trimmed = line.trim();

        if let Some(after) = trimmed.strip_prefix("rpc ") {
            if let Some(name) = after.split('(').next() {
                current_rpc = Some(name.trim().to_string());
            }
        }

        if trimmed.contains("google.api.http") {
            for method in &["post", "get", "put", "patch", "delete"] {
                if trimmed.contains(&format!("{}:", method)) {
                    if let Some(q) = trimmed.find('"') {
                        let start = q + 1;
                        if let Some(end) = trimmed[start..].find('"') {
                            let path = trimmed[start..start + end].to_string();
                            if let Some(ref rpc) = current_rpc {
                                routes.push((rpc.clone(), method.to_string(), path));
                            }
                            current_rpc = None;
                            break;
                        }
                    }
                }
            }
        }
    }

    let mut out = String::from(
        "// @generated by build.rs from proto/http/v1/auth.proto — do not edit\n\n",
    );
    for (rpc, method, path) in &routes {
        let const_name = format!("{}_PATH", pascal_to_screaming_snake(rpc));
        out.push_str(&format!("/// `{} {}` ({})\n", method.to_uppercase(), path, rpc));
        out.push_str(&format!("pub const {}: &str = \"{}\";\n", const_name, path));
    }

    std::fs::write(generated_dir.join("http_routes.rs"), &out)?;
    Ok(())
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let ws_root = workspace_root()?;
    let proto_root = ws_root.join("proto");
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR")?;
    let generated_dir = std::path::Path::new(&manifest_dir).join("src").join("generated");
    std::fs::create_dir_all(&generated_dir)?;

    let proto_file = proto_root.join("api/v1/auth.proto");

    tonic_build::configure()
        .build_server(true)
        .build_client(true)
        .out_dir(&generated_dir)
        .compile(&[&proto_file], &[&proto_root])?;

    // Compile http/v1/auth.proto — message types only (no server/client).
    // type_attribute adds serde derives so generated types work as Axum Json<T>.
    let http_proto_file = proto_root.join("http/v1/auth.proto");
    // `ccc` (dial-code) and `otp` were historically sent as bare JSON numbers
    // by the Vue frontend; match the lenient behaviour of the old mono (.NET)
    // RegistrationRequest which accepted both string and number for these fields.
    let string_or_number = "#[serde(deserialize_with = \"crate::serde_helpers::string_or_number::deserialize\")]";
    tonic_build::configure()
        .build_server(false)
        .build_client(false)
        .type_attribute(".", "#[derive(serde::Deserialize, serde::Serialize)]")
        .field_attribute(".", "#[serde(default)]")
        .field_attribute("RegisterRequest.ccc", string_or_number)
        .field_attribute("RegisterRequest.otp", string_or_number)
        .out_dir(&generated_dir)
        .compile(&[&http_proto_file], &[&proto_root])?;

    // Generate http_routes.rs from google.api.http annotations.
    generate_http_routes(&http_proto_file, &generated_dir)?;

    println!("cargo:rerun-if-changed={}", proto_file.display());
    println!("cargo:rerun-if-changed={}", http_proto_file.display());
    Ok(())
}
