CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230803224151_InitAuthDatabase') THEN
        IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'auth') THEN
            CREATE SCHEMA auth;
        END IF;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230803224151_InitAuthDatabase') THEN
    CREATE TABLE auth."_Role" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(256),
        "NormalizedName" character varying(256),
        "ConcurrencyStamp" text,
        CONSTRAINT "PK__Role" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230803224151_InitAuthDatabase') THEN
    CREATE TABLE auth."_Tag" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(128) NOT NULL DEFAULT (''::character varying),
        CONSTRAINT "_Tag_pk" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230803224151_InitAuthDatabase') THEN
    CREATE TABLE auth."_User" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "Uid" bigint NOT NULL,
        "PartyId" bigint NOT NULL,
        "TenantId" bigint NOT NULL,
        "ReferrerPartyId" bigint NOT NULL,
        "NativeName" character varying(128) NOT NULL,
        "FirstName" character varying(64) NOT NULL,
        "LastName" character varying(64) NOT NULL,
        "Language" character varying(20) NOT NULL,
        "Avatar" character varying(255) NOT NULL,
        "TimeZone" character varying(30) NOT NULL,
        "ReferCode" character varying(20) NOT NULL,
        "CountryCode" character varying(10) NOT NULL,
        "Currency" character varying(10) NOT NULL,
        "CCC" character varying(10) NOT NULL,
        "Birthday" date NOT NULL,
        "Gender" integer NOT NULL,
        "Citizen" character varying(32) NOT NULL,
        "Address" character varying(512) NOT NULL,
        "IdType" integer NOT NULL,
        "IdNumber" character varying(128) NOT NULL,
        "IdIssuer" character varying(128) NOT NULL,
        "IdIssuedOn" date NOT NULL,
        "IdExpireOn" date NOT NULL,
        "CreatedOn" timestamp with time zone NOT NULL,
        "UpdatedOn" timestamp with time zone NOT NULL,
        "LastLoginOn" timestamp with time zone,
        "RegisteredIp" character varying(64) NOT NULL,
        "ReferPath" text NOT NULL,
        "UserName" character varying(256),
        "NormalizedUserName" character varying(256),
        "Email" character varying(256),
        "NormalizedEmail" character varying(256),
        "EmailConfirmed" boolean NOT NULL,
        "PasswordHash" text,
        "SecurityStamp" text,
        "ConcurrencyStamp" text,
        "PhoneNumber" text,
        "PhoneNumberConfirmed" boolean NOT NULL,
        "TwoFactorEnabled" boolean NOT NULL,
        "LockoutEnd" timestamp with time zone,
        "LockoutEnabled" boolean NOT NULL,
        "AccessFailedCount" integer NOT NULL,
        CONSTRAINT "PK__User" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230803224151_InitAuthDatabase') THEN
    CREATE TABLE auth."_UserAudit" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "Type" integer NOT NULL,
        "RowId" bigint NOT NULL,
        "Action" integer NOT NULL,
        "PartyId" bigint NOT NULL,
        "CreatedOn" timestamp with time zone NOT NULL DEFAULT (now()),
        "Environment" text NOT NULL,
        "Data" text NOT NULL,
        CONSTRAINT "_UserAudit_pk" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230803224151_InitAuthDatabase') THEN
    CREATE TABLE auth."_RoleClaim" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "RoleId" bigint NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK__RoleClaim" PRIMARY KEY ("Id"),
        CONSTRAINT "FK__RoleClaim__Role_RoleId" FOREIGN KEY ("RoleId") REFERENCES auth."_Role" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230803224151_InitAuthDatabase') THEN
    CREATE TABLE auth."_UserClaim" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" bigint NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK__UserClaim" PRIMARY KEY ("Id"),
        CONSTRAINT "FK__UserClaim__User_UserId" FOREIGN KEY ("UserId") REFERENCES auth."_User" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230803224151_InitAuthDatabase') THEN
    CREATE TABLE auth."_UserLogin" (
        "LoginProvider" text NOT NULL,
        "ProviderKey" text NOT NULL,
        "ProviderDisplayName" text,
        "UserId" bigint NOT NULL,
        CONSTRAINT "PK__UserLogin" PRIMARY KEY ("LoginProvider", "ProviderKey"),
        CONSTRAINT "FK__UserLogin__User_UserId" FOREIGN KEY ("UserId") REFERENCES auth."_User" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230803224151_InitAuthDatabase') THEN
    CREATE TABLE auth."_UserRole" (
        "UserId" bigint NOT NULL,
        "RoleId" bigint NOT NULL,
        CONSTRAINT "PK__UserRole" PRIMARY KEY ("UserId", "RoleId"),
        CONSTRAINT "FK__UserRole__Role_RoleId" FOREIGN KEY ("RoleId") REFERENCES auth."_Role" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK__UserRole__User_UserId" FOREIGN KEY ("UserId") REFERENCES auth."_User" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230803224151_InitAuthDatabase') THEN
    CREATE TABLE auth."_UserTag" (
        "UserId" bigint NOT NULL,
        "TagId" bigint NOT NULL,
        CONSTRAINT "_UserTag_pk" PRIMARY KEY ("UserId", "TagId"),
        CONSTRAINT "_UserTag__Tag_Id_fk" FOREIGN KEY ("TagId") REFERENCES auth."_Tag" ("Id") ON DELETE CASCADE,
        CONSTRAINT "_UserTag__User_Id_fk" FOREIGN KEY ("UserId") REFERENCES auth."_User" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230803224151_InitAuthDatabase') THEN
    CREATE TABLE auth."_UserToken" (
        "UserId" bigint NOT NULL,
        "LoginProvider" text NOT NULL,
        "Name" text NOT NULL,
        "Value" text,
        CONSTRAINT "PK__UserToken" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
        CONSTRAINT "FK__UserToken__User_UserId" FOREIGN KEY ("UserId") REFERENCES auth."_User" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230803224151_InitAuthDatabase') THEN
    CREATE UNIQUE INDEX "RoleNameIndex" ON auth."_Role" ("NormalizedName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230803224151_InitAuthDatabase') THEN
    CREATE INDEX "IX__RoleClaim_RoleId" ON auth."_RoleClaim" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230803224151_InitAuthDatabase') THEN
    CREATE UNIQUE INDEX "_Tag_Name_ux" ON auth."_Tag" ("Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230803224151_InitAuthDatabase') THEN
    CREATE INDEX "EmailIndex" ON auth."_User" ("NormalizedEmail");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230803224151_InitAuthDatabase') THEN
    CREATE UNIQUE INDEX "IX__User_Uid" ON auth."_User" ("Uid");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230803224151_InitAuthDatabase') THEN
    CREATE UNIQUE INDEX "UserNameIndex" ON auth."_User" ("NormalizedUserName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230803224151_InitAuthDatabase') THEN
    CREATE INDEX "_UserAudit_PartyId_index" ON auth."_UserAudit" ("PartyId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230803224151_InitAuthDatabase') THEN
    CREATE INDEX "_UserAudit_Type_RowId_index" ON auth."_UserAudit" ("Type", "RowId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230803224151_InitAuthDatabase') THEN
    CREATE INDEX "IX__UserClaim_UserId" ON auth."_UserClaim" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230803224151_InitAuthDatabase') THEN
    CREATE INDEX "IX__UserLogin_UserId" ON auth."_UserLogin" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230803224151_InitAuthDatabase') THEN
    CREATE INDEX "IX__UserRole_RoleId" ON auth."_UserRole" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230803224151_InitAuthDatabase') THEN
    CREATE INDEX "IX__UserTag_TagId" ON auth."_UserTag" ("TagId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230803224151_InitAuthDatabase') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20230803224151_InitAuthDatabase', '8.0.21');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240119231850_RemoveAuthTag') THEN
    DROP TABLE auth."_UserTag";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240119231850_RemoveAuthTag') THEN
    DROP TABLE auth."_Tag";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240119231850_RemoveAuthTag') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20240119231850_RemoveAuthTag', '8.0.21');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240411011807_TidPidIdx') THEN
    ALTER TABLE auth."_User" ADD "Status" smallint NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240411011807_TidPidIdx') THEN
    CREATE INDEX "_User_PartyId_index" ON auth."_User" ("PartyId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240411011807_TidPidIdx') THEN
    CREATE INDEX "_User_Status_index" ON auth."_User" ("Status");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240411011807_TidPidIdx') THEN
    CREATE INDEX "_User_TenantId_index" ON auth."_User" ("TenantId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240411011807_TidPidIdx') THEN
    CREATE UNIQUE INDEX "_User_TenantId_PartyId_index" ON auth."_User" ("TenantId", "PartyId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240411011807_TidPidIdx') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20240411011807_TidPidIdx', '8.0.21');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240419232801_LastLoginIp') THEN
    ALTER TABLE auth."_User" ADD "LastLoginIp" character varying(64) NOT NULL DEFAULT (''::character varying);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240419232801_LastLoginIp') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20240419232801_LastLoginIp', '8.0.21');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240626191955_AuthPermission') THEN
    CREATE TABLE auth."_Permission" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "Action" character varying(256) NOT NULL DEFAULT (''::character varying),
        "Method" character varying(20) NOT NULL DEFAULT (''::character varying),
        "Category" character varying(50) NOT NULL DEFAULT (''::character varying),
        "Key" character varying(50) NOT NULL DEFAULT (''::character varying),
        "Auth" boolean NOT NULL,
        "CreatedOn" timestamp with time zone NOT NULL DEFAULT (now()),
        "UpdatedOn" timestamp with time zone NOT NULL DEFAULT (now()),
        CONSTRAINT _permission_pk PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240626191955_AuthPermission') THEN
    CREATE TABLE auth."_PermissionRoleAccess" (
        "RoleId" bigint NOT NULL,
        "PermissionId" bigint NOT NULL,
        CONSTRAINT "_PermissionRoleAccess_pk" PRIMARY KEY ("RoleId", "PermissionId"),
        CONSTRAINT "_PermissionUserAccess__Permission_fk" FOREIGN KEY ("PermissionId") REFERENCES auth."_Permission" ("Id") ON DELETE CASCADE,
        CONSTRAINT "_PermissionUserAccess__RoleId_fk" FOREIGN KEY ("RoleId") REFERENCES auth."_Role" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240626191955_AuthPermission') THEN
    CREATE TABLE auth."_PermissionUserAccess" (
        "UserId" bigint NOT NULL,
        "PermissionId" bigint NOT NULL,
        CONSTRAINT "_PermissionUserAccess_pk" PRIMARY KEY ("UserId", "PermissionId"),
        CONSTRAINT "_PermissionUserAccess__Permission_fk" FOREIGN KEY ("PermissionId") REFERENCES auth."_Permission" ("Id") ON DELETE CASCADE,
        CONSTRAINT "_PermissionUserAccess__UserId_fk" FOREIGN KEY ("UserId") REFERENCES auth."_User" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240626191955_AuthPermission') THEN
    CREATE INDEX "_Permission_Action_index" ON auth."_Permission" ("Action");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240626191955_AuthPermission') THEN
    CREATE INDEX "_Permission_Category_index" ON auth."_Permission" ("Category");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240626191955_AuthPermission') THEN
    CREATE INDEX "_Permission_Method_index" ON auth."_Permission" ("Method");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240626191955_AuthPermission') THEN
    CREATE INDEX "IX__PermissionRoleAccess_PermissionId" ON auth."_PermissionRoleAccess" ("PermissionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240626191955_AuthPermission') THEN
    CREATE INDEX "IX__PermissionUserAccess_PermissionId" ON auth."_PermissionUserAccess" ("PermissionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240626191955_AuthPermission') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20240626191955_AuthPermission', '8.0.21');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260227061533_AddOpenIddictTables') THEN
        IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'identity') THEN
            CREATE SCHEMA identity;
        END IF;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260227061533_AddOpenIddictTables') THEN
    CREATE TABLE identity."OpenIddictApplications" (
        "Id" text NOT NULL,
        "ApplicationType" text,
        "ClientId" text,
        "ClientSecret" text,
        "ClientType" text,
        "ConcurrencyToken" text,
        "ConsentType" text,
        "DisplayName" text,
        "DisplayNames" text,
        "JsonWebKeySet" text,
        "Permissions" text,
        "PostLogoutRedirectUris" text,
        "Properties" text,
        "RedirectUris" text,
        "Requirements" text,
        "Settings" text,
        CONSTRAINT "PK_OpenIddictApplications" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260227061533_AddOpenIddictTables') THEN
    CREATE TABLE identity."OpenIddictScopes" (
        "Id" text NOT NULL,
        "ConcurrencyToken" text,
        "Description" text,
        "Descriptions" text,
        "DisplayName" text,
        "DisplayNames" text,
        "Name" text,
        "Properties" text,
        "Resources" text,
        CONSTRAINT "PK_OpenIddictScopes" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260227061533_AddOpenIddictTables') THEN
    CREATE TABLE identity."OpenIddictAuthorizations" (
        "Id" text NOT NULL,
        "ApplicationId" text,
        "ConcurrencyToken" text,
        "CreationDate" timestamp with time zone,
        "Properties" text,
        "Scopes" text,
        "Status" text,
        "Subject" text,
        "Type" text,
        CONSTRAINT "PK_OpenIddictAuthorizations" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_OpenIddictAuthorizations_OpenIddictApplications_Application~" FOREIGN KEY ("ApplicationId") REFERENCES identity."OpenIddictApplications" ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260227061533_AddOpenIddictTables') THEN
    CREATE TABLE identity."OpenIddictTokens" (
        "Id" text NOT NULL,
        "ApplicationId" text,
        "AuthorizationId" text,
        "ConcurrencyToken" text,
        "CreationDate" timestamp with time zone,
        "ExpirationDate" timestamp with time zone,
        "Payload" text,
        "Properties" text,
        "RedemptionDate" timestamp with time zone,
        "ReferenceId" text,
        "Status" text,
        "Subject" text,
        "Type" text,
        CONSTRAINT "PK_OpenIddictTokens" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_OpenIddictTokens_OpenIddictApplications_ApplicationId" FOREIGN KEY ("ApplicationId") REFERENCES identity."OpenIddictApplications" ("Id"),
        CONSTRAINT "FK_OpenIddictTokens_OpenIddictAuthorizations_AuthorizationId" FOREIGN KEY ("AuthorizationId") REFERENCES identity."OpenIddictAuthorizations" ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260227061533_AddOpenIddictTables') THEN
    CREATE INDEX "IX_OpenIddictAuthorizations_ApplicationId" ON identity."OpenIddictAuthorizations" ("ApplicationId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260227061533_AddOpenIddictTables') THEN
    CREATE INDEX "IX_OpenIddictTokens_ApplicationId" ON identity."OpenIddictTokens" ("ApplicationId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260227061533_AddOpenIddictTables') THEN
    CREATE INDEX "IX_OpenIddictTokens_AuthorizationId" ON identity."OpenIddictTokens" ("AuthorizationId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260227061533_AddOpenIddictTables') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260227061533_AddOpenIddictTables', '8.0.21');
    END IF;
END $EF$;
COMMIT;

