// <auto-generated />
using System;
using Bacera.Gateway;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bacera.Gateway.Data.Migrations.CentralDb
{
    [DbContext(typeof(CentralDbContext))]
    [Migration("20240129234136_CentralDbInit2")]
    partial class CentralDbInit2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Bacera.Gateway.CentralAccount", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AccountId")
                        .HasColumnType("bigint");

                    b.Property<long>("AccountNumber")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("ServiceId")
                        .HasColumnType("integer");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<long>("Uid")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("_PrimeKey");

                    b.HasIndex(new[] { "TenantId", "ServiceId", "AccountId", "AccountNumber" }, "_CentralAccount_Ids_Index");

                    b.HasIndex(new[] { "Uid" }, "_CentralAccount_Uid_Index");

                    b.ToTable("_CentralAccount", "trd");
                });

            modelBuilder.Entity("Bacera.Gateway.CentralParty", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("NativeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("SiteId")
                        .HasColumnType("integer");

                    b.Property<long>("Uid")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("_CentralParty_PrimeKey");

                    b.HasIndex(new[] { "Code" }, "_CentralParty_Code_Index");

                    b.HasIndex(new[] { "Email" }, "_CentralParty_Email_Index");

                    b.HasIndex(new[] { "NativeName" }, "_CentralParty_NativeName_Index");

                    b.HasIndex(new[] { "SiteId" }, "_CentralParty_SiteId_Index");

                    b.HasIndex(new[] { "Uid" }, "_CentralParty_Uid_Index");

                    b.ToTable("_CentralParty", "core");
                });

            modelBuilder.Entity("Bacera.Gateway.CentralReferralCode", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AccountId")
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("PartyId")
                        .HasColumnType("bigint");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("_CentralReferralCode_PrimeKey");

                    b.HasIndex(new[] { "AccountId" }, "_CentralReferralCode_AccountId_Index");

                    b.HasIndex(new[] { "Code" }, "_CentralReferralCode_Code_Index");

                    b.HasIndex(new[] { "Name" }, "_CentralReferralCode_Name_Index");

                    b.HasIndex(new[] { "PartyId" }, "_CentralReferralCode_PartyId_Index");

                    b.HasIndex(new[] { "TenantId" }, "_CentralReferralCode_TenantId_Index");

                    b.ToTable("_CentralReferralCode", "core");
                });

            modelBuilder.Entity("Bacera.Gateway.Domain", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));
                    NpgsqlPropertyBuilderExtensions.HasIdentityOptions(b.Property<long>("Id"), 10000L, null, null, null, null, null);

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DomainName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("domain_pkey");

                    b.HasIndex(new[] { "TenantId" }, "IX_domains_tenant_id");

                    b.HasIndex(new[] { "DomainName" }, "UX_Domain_DomainName")
                        .IsUnique();

                    b.ToTable("_Domain", "core");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DomainName = "demo.localhost",
                            TenantId = 1L,
                            UpdatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Bacera.Gateway.Tenant", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));
                    NpgsqlPropertyBuilderExtensions.HasIdentityOptions(b.Property<long>("Id"), 10000L, null, null, null, null, null);

                    b.Property<bool>("ApiLogEnable")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DatabaseName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("UpdatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("tenant_pkey");

                    b.ToTable("_Tenant", "core");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ApiLogEnable = false,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DatabaseName = "portal_tenant_1",
                            Name = "Demo Tenant",
                            UpdatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Bacera.Gateway.CentralAccount", b =>
                {
                    b.HasOne("Bacera.Gateway.Tenant", "Tenant")
                        .WithMany("CentralAccounts")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("_CentralAccount_TenantId_Foreign");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Bacera.Gateway.CentralReferralCode", b =>
                {
                    b.HasOne("Bacera.Gateway.Tenant", "Tenant")
                        .WithMany("CentralReferralCodes")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("_CentralReferralCode_TenantId_Foreign");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Bacera.Gateway.Domain", b =>
                {
                    b.HasOne("Bacera.Gateway.Tenant", "Tenant")
                        .WithMany("Domains")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("core_domain_tenant_id_foreign");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Bacera.Gateway.Tenant", b =>
                {
                    b.Navigation("CentralAccounts");

                    b.Navigation("CentralReferralCodes");

                    b.Navigation("Domains");
                });
#pragma warning restore 612, 618
        }
    }
}
