// <auto-generated />
using System;
using Bacera.Gateway;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bacera.Gateway.Data.Migrations.CentralDb
{
    [DbContext(typeof(CentralDbContext))]
    partial class CentralDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Bacera.Gateway.Central.CentralConfig", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DataFormat")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<long>("RowId")
                        .HasColumnType("bigint");

                    b.Property<long>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("_CentralConfig_pk");

                    b.HasIndex(new[] { "Category" }, "IX__CentralConfig_Category");

                    b.HasIndex(new[] { "DataFormat" }, "IX__CentralConfig_DataFormat");

                    b.HasIndex(new[] { "Key" }, "IX__CentralConfig_Key");

                    b.HasIndex(new[] { "RowId" }, "IX__CentralConfig_RowId");

                    b.ToTable("_CentralConfig", "core");
                });

            modelBuilder.Entity("Bacera.Gateway.CentralAccount", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AccountId")
                        .HasColumnType("bigint");

                    b.Property<long>("AccountNumber")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("ServiceId")
                        .HasColumnType("integer");

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<long>("Uid")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("_PrimeKey");

                    b.HasIndex(new[] { "TenantId", "ServiceId", "AccountId", "AccountNumber" }, "_CentralAccount_Ids_Index");

                    b.HasIndex(new[] { "Uid" }, "_CentralAccount_Uid_Index");

                    b.ToTable("_CentralAccount", "trd");
                });

            modelBuilder.Entity("Bacera.Gateway.CentralApiLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(256)
                        .HasColumnType("character varying")
                        .HasDefaultValueSql("''::character varying");

                    b.Property<string>("ConnectionId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(256)
                        .HasColumnType("character varying")
                        .HasDefaultValueSql("''::character varying");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Ip")
                        .HasColumnType("text");

                    b.Property<string>("Method")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(12)
                        .HasColumnType("character varying")
                        .HasDefaultValueSql("''::character varying");

                    b.Property<string>("Parameters")
                        .HasColumnType("text");

                    b.Property<long>("PartyId")
                        .HasColumnType("bigint");

                    b.Property<string>("Referer")
                        .HasColumnType("text");

                    b.Property<string>("RequestContent")
                        .HasColumnType("text");

                    b.Property<string>("ResponseContent")
                        .HasColumnType("text");

                    b.Property<int>("StatusCode")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("apiLog_pkey");

                    b.HasIndex(new[] { "Action" }, "_ApiLog_Action_index");

                    b.HasIndex(new[] { "ConnectionId" }, "_ApiLog_ConnectionId_index");

                    b.HasIndex(new[] { "Ip" }, "_ApiLog_Ip_index");

                    b.HasIndex(new[] { "Method" }, "_ApiLog_Method_index");

                    b.HasIndex(new[] { "PartyId" }, "_ApiLog_PartyId_index");

                    b.HasIndex(new[] { "StatusCode" }, "_ApiLog_StatusCode_index");

                    b.ToTable("_ApiLog", "core");
                });

            modelBuilder.Entity("Bacera.Gateway.CentralParty", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("NativeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("SiteId")
                        .HasColumnType("integer");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<long>("Tid")
                        .HasColumnType("bigint");

                    b.Property<long>("Uid")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("_CentralParty_PrimeKey");

                    b.HasIndex(new[] { "Code" }, "_CentralParty_Code_Index");

                    b.HasIndex(new[] { "Email" }, "_CentralParty_Email_Index");

                    b.HasIndex(new[] { "NativeName" }, "_CentralParty_NativeName_Index");

                    b.HasIndex(new[] { "SiteId" }, "_CentralParty_SiteId_Index");

                    b.HasIndex(new[] { "Uid" }, "_CentralParty_Uid_Index");

                    b.ToTable("_CentralParty", "core");
                });

            modelBuilder.Entity("Bacera.Gateway.CentralReferralCode", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AccountId")
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValueSql("''::character varying");

                    b.Property<long>("PartyId")
                        .HasColumnType("bigint");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("_CentralReferralCode_PrimeKey");

                    b.HasIndex(new[] { "AccountId" }, "_CentralReferralCode_AccountId_Index");

                    b.HasIndex(new[] { "Code" }, "_CentralReferralCode_Code_Index");

                    b.HasIndex(new[] { "Name" }, "_CentralReferralCode_Name_Index");

                    b.HasIndex(new[] { "PartyId" }, "_CentralReferralCode_PartyId_Index");

                    b.HasIndex(new[] { "TenantId" }, "_CentralReferralCode_TenantId_Index");

                    b.ToTable("_CentralReferralCode", "core");
                });

            modelBuilder.Entity("Bacera.Gateway.CentralTradeService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Configuration")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<short>("IsAllowAccountCreation")
                        .HasColumnType("smallint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<short>("Platform")
                        .HasColumnType("smallint");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.ToTable("_CentralTradeService", "trd");
                });

            modelBuilder.Entity("Bacera.Gateway.Domain", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));
                    NpgsqlPropertyBuilderExtensions.HasIdentityOptions(b.Property<long>("Id"), 10000L, null, null, null, null, null);

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DomainName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("domain_pkey");

                    b.HasIndex(new[] { "TenantId" }, "IX_domains_tenant_id");

                    b.HasIndex(new[] { "DomainName" }, "UX_Domain_DomainName")
                        .IsUnique();

                    b.ToTable("_Domain", "core");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DomainName = "demo.localhost",
                            TenantId = 1L,
                            UpdatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Bacera.Gateway.IpBlackList", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));
                    NpgsqlPropertyBuilderExtensions.HasIdentityOptions(b.Property<long>("Id"), 10000L, null, null, null, null, null);

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasDefaultValueSql("''::character varying");

                    b.Property<string>("Note")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasDefaultValueSql("''::character varying");

                    b.Property<string>("OperatorName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasDefaultValueSql("''::character varying");

                    b.Property<DateTime>("UpdatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("ip_black_lists_pkey");

                    b.HasIndex(new[] { "Ip" }, "_IpBlackList_Ip_Index")
                        .IsUnique();

                    b.HasIndex(new[] { "OperatorName" }, "_IpBlackList_OperatorName_Index");

                    b.ToTable("_IpBlackList", "core");
                });

            modelBuilder.Entity("Bacera.Gateway.MetaTrade", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));
                    NpgsqlPropertyBuilderExtensions.HasIdentityOptions(b.Property<long>("Id"), 10000L, null, null, null, null, null);

                    b.Property<long>("AccountNumber")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CloseAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("ClosePrice")
                        .HasColumnType("double precision");

                    b.Property<int>("Cmd")
                        .HasColumnType("integer");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Commission")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<double>("CurrentPrice")
                        .HasColumnType("double precision");

                    b.Property<int>("Digits")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("OpenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("OpenPrice")
                        .HasColumnType("double precision");

                    b.Property<long?>("Position")
                        .HasColumnType("bigint");

                    b.Property<double>("Profit")
                        .HasColumnType("double precision");

                    b.Property<int>("Reason")
                        .HasColumnType("integer");

                    b.Property<int>("ServiceId")
                        .HasColumnType("integer");

                    b.Property<double>("Sl")
                        .HasColumnType("double precision");

                    b.Property<double>("Swaps")
                        .HasColumnType("double precision");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<long>("Ticket")
                        .HasColumnType("bigint");

                    b.Property<long>("TimeStamp")
                        .HasColumnType("bigint");

                    b.Property<double>("Tp")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("UpdatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<double>("Volume")
                        .HasColumnType("double precision");

                    b.Property<int>("VolumeOriginal")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("meta_trade_trade_pkey");

                    b.HasIndex(new[] { "AccountNumber" }, "IX_meta_trade_trade_account_number");

                    b.HasIndex(new[] { "CloseAt" }, "IX_meta_trade_trade_close_at");

                    b.HasIndex(new[] { "Cmd" }, "IX_meta_trade_trade_cmd");

                    b.HasIndex(new[] { "OpenAt" }, "IX_meta_trade_trade_open_at");

                    b.HasIndex(new[] { "ServiceId" }, "IX_meta_trade_trade_service_id");

                    b.HasIndex(new[] { "ServiceId", "Ticket" }, "IX_meta_trade_trade_service_id_ticket")
                        .IsUnique();

                    b.HasIndex(new[] { "Symbol" }, "IX_meta_trade_trade_symbol");

                    b.HasIndex(new[] { "TenantId" }, "IX_meta_trade_trade_tenant_id");

                    b.HasIndex(new[] { "Ticket" }, "IX_meta_trade_trade_ticket");

                    b.HasIndex(new[] { "TimeStamp" }, "IX_meta_trade_trade_time_stamp");

                    b.ToTable("_MetaTrade", "trd");
                });

            modelBuilder.Entity("Bacera.Gateway.Tenant", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));
                    NpgsqlPropertyBuilderExtensions.HasIdentityOptions(b.Property<long>("Id"), 10000L, null, null, null, null, null);

                    b.Property<bool>("ApiLogEnable")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DatabaseName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("UpdatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("tenant_pkey");

                    b.ToTable("_Tenant", "core");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ApiLogEnable = false,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DatabaseName = "portal_tenant_1",
                            Name = "Demo Tenant",
                            UpdatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Bacera.Gateway.UserBlackList", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));
                    NpgsqlPropertyBuilderExtensions.HasIdentityOptions(b.Property<long>("Id"), 10000L, null, null, null, null, null);

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasDefaultValueSql("''::character varying");

                    b.Property<string>("IdNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasDefaultValueSql("''::character varying");

                    b.Property<string>("OperatorName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasDefaultValueSql("''::character varying");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasDefaultValueSql("''::character varying");

                    b.Property<DateTime>("UpdatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("user_black_lists_pkey");

                    b.HasIndex(new[] { "Email" }, "_UserBlackList_Email_Index");

                    b.HasIndex(new[] { "IdNumber" }, "_UserBlackList_IdNumber_Index");

                    b.HasIndex(new[] { "Name" }, "_UserBlackList_Name_Index");

                    b.HasIndex(new[] { "OperatorName" }, "_UserBlackList_OperatorName_Index");

                    b.HasIndex(new[] { "Phone" }, "_UserBlackList_Phone_Index");

                    b.ToTable("_UserBlackList", "core");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text");

                    b.Property<string>("Xml")
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("DataProtectionKeys_pkey");

                    b.ToTable("DataProtectionKeys", "core");
                });

            modelBuilder.Entity("Bacera.Gateway.CentralAccount", b =>
                {
                    b.HasOne("Bacera.Gateway.Tenant", "Tenant")
                        .WithMany("CentralAccounts")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("_CentralAccount_TenantId_Foreign");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Bacera.Gateway.CentralReferralCode", b =>
                {
                    b.HasOne("Bacera.Gateway.Tenant", "Tenant")
                        .WithMany("CentralReferralCodes")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("_CentralReferralCode_TenantId_Foreign");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Bacera.Gateway.Domain", b =>
                {
                    b.HasOne("Bacera.Gateway.Tenant", "Tenant")
                        .WithMany("Domains")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("core_domain_tenant_id_foreign");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Bacera.Gateway.MetaTrade", b =>
                {
                    b.HasOne("Bacera.Gateway.Tenant", "Tenant")
                        .WithMany("CentralTrades")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("trd_meta_trade_trade_tenant_id_foreign");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Bacera.Gateway.Tenant", b =>
                {
                    b.Navigation("CentralAccounts");

                    b.Navigation("CentralReferralCodes");

                    b.Navigation("CentralTrades");

                    b.Navigation("Domains");
                });
#pragma warning restore 612, 618
        }
    }
}
