namespace Bacera.Gateway;

public class RebateSymbol
{
    public string Code { get; set; } = string.Empty;
    public string Category { get; set; } = string.Empty;
    public int CategoryId { get; set; }

    // private static RebateSymbol build(string code, int categoryId, string category)
    //     => new RebateSymbol
    //     {
    //         Code = code,
    //         Category = category,
    //         CategoryId = categoryId,
    //     };

    // public static readonly List<KeyValuePair<int, string>> Categories = new()
    // {
    //     // new KeyValuePair<int, string>(1, "Commodity"),
    //     // new KeyValuePair<int, string>(2, "Forex"),
    //     // new KeyValuePair<int, string>(3, "D Forex"),
    //     // new KeyValuePair<int, string>(4, "Index"),
    //     // new KeyValuePair<int, string>(5, "Stock"),
    //     // new KeyValuePair<int, string>(6, "Precious Metal"),
    //     //
    //     // new KeyValuePair<int, string>(10, "Crypto"),
    //     // new KeyValuePair<int, string>(11, "Special Commodity"),
    //     // new KeyValuePair<int, string>(12, "Special Forex"),
    //     // new KeyValuePair<int, string>(13, "Special D Forex"),
    //     // new KeyValuePair<int, string>(14, "Special Index"),
    //     // new KeyValuePair<int, string>(16, "Special Precious Metal"),
    //
    //     new KeyValuePair<int, string>(1, "D Forex"),
    //     new KeyValuePair<int, string>(2, "Forex"),
    //     new KeyValuePair<int, string>(3, "Gold"),
    //     new KeyValuePair<int, string>(4, "Silver 5000OZ"),
    //     new KeyValuePair<int, string>(5, "Silver 1000OZ"),
    //     new KeyValuePair<int, string>(6, "OIL"),
    //     new KeyValuePair<int, string>(7, "Natural Gas"),
    //     new KeyValuePair<int, string>(8, "Commodities"),
    //     new KeyValuePair<int, string>(9, "HKG50"),
    //     new KeyValuePair<int, string>(10, "A50"),
    //     new KeyValuePair<int, string>(11, "JPN225"),
    //     new KeyValuePair<int, string>(12, "US500"),
    //     new KeyValuePair<int, string>(13, "US30"),
    //     new KeyValuePair<int, string>(14, "US100"),
    //     new KeyValuePair<int, string>(15, "Shares"),
    //     new KeyValuePair<int, string>(16, "Crypto"),
    // };
    //
    // public static readonly List<RebateSymbol> ClientAll =
    // [
    //     build("EURUSD", 1, "D Forex"),
    //     build("USDJPY", 1, "D Forex"),
    //     build("AUDUSD", 1, "D Forex"),
    //     build("GBPUSD", 1, "D Forex"),
    //     build("NZDUSD", 1, "D Forex"),
    //     build("USDCAD", 1, "D Forex"),
    //     build("USDCHF", 1, "D Forex"),
    //
    //     build("EURCHF", 2, "Forex"),
    //     build("EURGBP", 2, "Forex"),
    //     build("EURJPY", 2, "Forex"),
    //     build("CADJPY", 2, "Forex"),
    //     build("AUDNZD", 2, "Forex"),
    //     build("AUDJPY", 2, "Forex"),
    //     build("GBPCHF", 2, "Forex"),
    //     build("GBPJPY", 2, "Forex"),
    //     build("CADCHF", 2, "Forex"),
    //     build("GBPAUD", 2, "Forex"),
    //     build("CHFJPY", 2, "Forex"),
    //     build("AUDCAD", 2, "Forex"),
    //     build("EURAUD", 2, "Forex"),
    //     build("EURCAD", 2, "Forex"),
    //     build("NZDJPY", 2, "Forex"),
    //     build("AUDCHF", 2, "Forex"),
    //     build("NZDCHF", 2, "Forex"),
    //     build("GBPNZD", 2, "Forex"),
    //     build("GBPCAD", 2, "Forex"),
    //     build("NZDCAD", 2, "Forex"),
    //     build("EURNZD", 2, "Forex"),
    //     build("USDCNH", 2, "Forex"),
    //     build("USDMXN", 2, "Forex"),
    //     build("USDNOK", 2, "Forex"),
    //     build("USDSEK", 2, "Forex"),
    //     build("USDTRY", 2, "Forex"),
    //     build("USDZAR", 2, "Forex"),
    //     build("EURNOK", 2, "Forex"),
    //     build("EURSEK", 2, "Forex"),
    //     build("EURTRY", 2, "Forex"),
    //
    //     build("XAUUSD", 3, "Gold"),
    //
    //     build("XAGUSD", 4, "Silver 5000OZ"),
    //     build("XAGUSDmin", 5, "Silver 1000OZ"),
    //     build("XAGUSDMIN", 5, "Silver 1000OZ"),
    //     build("#CL", 6, "OIL"),
    //     build("#CLF24", 6, "OIL"),
    //     build("XTIUSD", 6, "OIL"),
    //     build("XBRUSD", 6, "OIL"),
    //     build("#BRN", 6, "OIL"),
    //     build("XNGUSD", 7, "Natural Gas"),
    //     build("#AUS200", 8, "Commodities"),
    //     build("#GER40", 8, "Commodities"),
    //     build("#EUSTX50", 8, "Commodities"),
    //     build("#ESP35", 8, "Commodities"),
    //     build("#FRA40", 8, "Commodities"),
    //     build("#UK100", 8, "Commodities"),
    //     build("#HKG50", 9, "HKG50"),
    //     build("#CHN50", 10, "A50"),
    //     build("#JPN225", 11, "JPN225"),
    //     build("#US500", 12, "US500"),
    //     build("#US30", 13, "US30"),
    //     build("#US100", 14, "US100"),
    //     build("#AAPL", 15, "Shares"),
    //     build("#AXP", 15, "Shares"),
    //     build("#BAC", 15, "Shares"),
    //     build("#C", 15, "Shares"),
    //     build("#DIS", 15, "Shares"),
    //     build("#IBM", 15, "Shares"),
    //     build("#INTC", 15, "Shares"),
    //     build("#KO", 15, "Shares"),
    //     build("#MCD", 15, "Shares"),
    //     build("#MSFT", 15, "Shares"),
    //     build("#BA", 15, "Shares"),
    //     build("#QAN.AX", 15, "Shares"),
    //     build("#CSL.AX", 15, "Shares"),
    //     build("#BHP.AX", 15, "Shares"),
    //     build("#6501.T", 15, "Shares"),
    //     build("#6502.T", 15, "Shares"),
    //     build("#7201.T", 15, "Shares"),
    //     build("#7261.T", 15, "Shares"),
    //     build("#8306.T", 15, "Shares"),
    //     build("#NVDA", 15, "Shares"),
    //     build("Bitcoin", 16, "Crypto"),
    //     build("Ethereum", 16, "Crypto"),
    //     build("BITCOIN", 16, "Crypto"),
    //     build("ETHEREUM", 16, "Crypto")
    // ];

    // public static readonly List<RebateSymbol> All =
    // [
    //     build("EURUSD", 3, "D Forex"),
    //     build("GBPUSD", 3, "D Forex"),
    //     build("AUDUSD", 3, "D Forex"),
    //     build("USDCAD", 3, "D Forex"),
    //     build("USDJPY", 3, "D Forex"),
    //     build("NZDUSD", 3, "D Forex"),
    //     build("USDCHF", 3, "D Forex"),
    //     build("AUDCAD", 2, "Forex"),
    //     build("AUDJPY", 2, "Forex"),
    //     build("CADJPY", 2, "Forex"),
    //     build("CHFJPY", 2, "Forex"),
    //     build("EURAUD", 2, "Forex"),
    //     build("EURCAD", 2, "Forex"),
    //     build("EURCHF", 2, "Forex"),
    //     build("EURGBP", 2, "Forex"),
    //     build("EURJPY", 2, "Forex"),
    //     build("EURNZD", 2, "Forex"),
    //     build("GBPCHF", 2, "Forex"),
    //     build("GBPJPY", 2, "Forex"),
    //     build("NZDCAD", 2, "Forex"),
    //     build("NZDJPY", 2, "Forex"),
    //     build("USDCNH", 2, "Forex"),
    //     build("AUDNZD", 2, "Forex"),
    //     build("NZDCHF", 2, "Forex"),
    //     build("GBPCAD", 2, "Forex"),
    //     build("GBPNZD", 2, "Forex"),
    //     build("GBPAUD", 2, "Forex"),
    //     build("AUDCHF", 2, "Forex"),
    //     build("CADCHF", 2, "Forex"),
    //     build("USDMXN", 2, "Forex"),
    //     build("USDNOK", 2, "Forex"),
    //     build("USDSEK", 2, "Forex"),
    //     build("USDTRY", 2, "Forex"),
    //     build("USDZAR", 2, "Forex"),
    //     build("EURNOK", 2, "Forex"),
    //     build("EURSEK", 2, "Forex"),
    //     build("EURTRY", 2, "Forex"),
    //     build("XAUUSD", 6, "Precious Metal"),
    //     build("XAGUSD", 6, "Precious Metal"),
    //     build("XPTUSD", 6, "Precious Metal"),
    //     build("XAGUSDMIN", 6, "Precious Metal"),
    //     build("SILVER.", 6, "Precious Metal"),
    //     build("GOLD.", 6, "Precious Metal"),
    //     build("SILVER->", 6, "Precious Metal"),
    //     build("GOLD->", 6, "Precious Metal"),
    //
    //     build("XTIUSD", 1, "Commodity"),
    //     build("XBRUSD", 1, "Commodity"),
    //     build("XNGUSD", 1, "Commodity"),
    //     build("#CL", 1, "Commodity"),
    //     build("#BRN", 1, "Commodity"),
    //     build("USOIL", 1, "Commodity"),
    //     build("#JPN225", 4, "Index"),
    //     build("#US500", 4, "Index"),
    //     build("#US30", 4, "Index"),
    //     build("#US100", 4, "Index"),
    //     build("#AUS200", 4, "Index"),
    //     build("#GER40", 4, "Index"),
    //     build("#EUSTX50", 4, "Index"),
    //     build("#ESP35", 4, "Index"),
    //     build("#FRA40", 4, "Index"),
    //     build("#UK100", 4, "Index"),
    //     build("#CHN50", 4, "Index"),
    //     build("#HKG50", 4, "Index"),
    //     build("#AAPL", 5, "Stock"),
    //     build("#AXP", 5, "Stock"),
    //     build("#BAC", 5, "Stock"),
    //     build("#C", 5, "Stock"),
    //     build("#DIS", 5, "Stock"),
    //     build("#IBM", 5, "Stock"),
    //     build("#INTC", 5, "Stock"),
    //     build("#KO", 5, "Stock"),
    //     build("#MCD", 5, "Stock"),
    //     build("#MSFT", 5, "Stock"),
    //     build("#BA", 5, "Stock"),
    //     build("#QAN.AX", 5, "Stock"),
    //     build("#APT.AX", 5, "Stock"),
    //     build("#CSL.AX", 5, "Stock"),
    //     build("#BHP.AX", 5, "Stock"),
    //     build("#6501.T", 5, "Stock"),
    //     build("#6502.T", 5, "Stock"),
    //     build("#7201.T", 5, "Stock"),
    //     build("#7261.T", 5, "Stock"),
    //     build("#8306.T", 5, "Stock"),
    //     build("#0005.HK", 5, "Stock"),
    //     build("#0291.HK", 5, "Stock"),
    //     build("#0700.HK", 5, "Stock"),
    //     build("#0728.HK", 5, "Stock"),
    //     build("#0941.HK", 5, "Stock"),
    //     build("#1088.HK", 5, "Stock"),
    //     build("#1810.HK", 5, "Stock"),
    //     build("#1928.HK", 5, "Stock"),
    //     build("#2628.HK", 5, "Stock"),
    //     build("#3328.HK", 5, "Stock"),
    //     build("#3988.HK", 5, "Stock"),
    //     build("#NVDA", 5, "Stock"),
    //     build("#TSLA", 5, "Stock"),
    //     build("#BABA", 5, "Stock"),
    //     build("Bitcoin", 10, "Crypto"),
    //     build("Ethereum", 10, "Crypto"),
    //     build("EURUSD.", 13, "Special D Forex"),
    //     build("GBPUSD.", 13, "Special D Forex"),
    //     build("AUDUSD.", 13, "Special D Forex"),
    //     build("USDCAD.", 13, "Special D Forex"),
    //     build("USDJPY.", 13, "Special D Forex"),
    //     build("NZDUSD.", 13, "Special D Forex"),
    //     build("USDCHF.", 13, "Special D Forex"),
    //     build("AUDCAD.", 13, "Special Forex"),
    //     build("AUDJPY.", 13, "Special Forex"),
    //     build("CADJPY.", 13, "Special Forex"),
    //     build("CHFJPY.", 13, "Special Forex"),
    //     build("EURAUD.", 13, "Special Forex"),
    //     build("EURCAD.", 13, "Special Forex"),
    //     build("EURCHF.", 13, "Special Forex"),
    //     build("EURGBP.", 13, "Special Forex"),
    //     build("EURJPY.", 13, "Special Forex"),
    //     build("EURNZD.", 13, "Special Forex"),
    //     build("GBPCHF.", 13, "Special Forex"),
    //     build("GBPJPY.", 13, "Special Forex"),
    //     build("NZDCAD.", 13, "Special Forex"),
    //     build("NZDJPY.", 13, "Special Forex"),
    //     build("USDCNH.", 13, "Special Forex"),
    //     build("AUDNZD.", 13, "Special Forex"),
    //     build("NZDCHF.", 13, "Special Forex"),
    //     build("GBPCAD.", 13, "Special Forex"),
    //     build("GBPNZD.", 13, "Special Forex"),
    //     build("GBPAUD.", 13, "Special Forex"),
    //     build("AUDCHF.", 13, "Special Forex"),
    //     build("CADCHF.", 13, "Special Forex"),
    //     build("USDMXN.", 13, "Special Forex"),
    //     build("USDNOK.", 13, "Special Forex"),
    //     build("USDSEK.", 13, "Special Forex"),
    //     build("USDTRY.", 13, "Special Forex"),
    //     build("USDZAR.", 13, "Special Forex"),
    //     build("EURNOK.", 13, "Special Forex"),
    //     build("EURSEK.", 13, "Special Forex"),
    //     build("EURTRY.", 13, "Special Forex"),
    //     build("XAUUSD.", 16, "Special Precious Metal"),
    //     build("XAGUSD.", 16, "Special Precious Metal"),
    //     build("XAGUSDMIN.", 16, "Special Precious Metal"),
    //     build("XTIUSD.", 11, "Special Commodity"),
    //     build("XBRUSD.", 11, "Special Commodity"),
    //     build("XNGUSD.", 11, "Special Commodity"),
    //     build("#JPN225.", 14, "Special Index"),
    //     build("#US500.", 14, "Special Index"),
    //     build("#US30.", 14, "Special Index"),
    //     build("#US100.", 14, "Special Index"),
    //     build("#AUS200.", 14, "Special Index"),
    //     build("#GER40.", 14, "Special Index"),
    //     build("#EUSTX50.", 14, "Special Index"),
    //     build("#ESP35.", 14, "Special Index"),
    //     build("#FRA40.", 14, "Special Index"),
    //     build("#UK100.", 14, "Special Index"),
    //     build("#CHN50.", 14, "Special Index"),
    //     build("#HKG50.", 14, "Special Index")
    // ];
}
//
// public static class RebateSymbolExtensions
// {
//     public static List<string> Codes(this IEnumerable<RebateSymbol> symbols)
//         => symbols.Select(x => x.Code).ToList();
// }