// Auth actions
export {
  login,
  logout,
  register,
  getMe,
  forgotPassword,
  resetPassword,
  resendConfirmation,
  setToken,
  setLocale,
  getSiteConfig,
  createDemoAccountFromNonAuth,
  confirmEmail,
  verify2FA,
} from './auth';

// User actions
export { 
  getUserInfo, 
  getConfiguration,
  uploadAvatar,
  sendPhoneVerificationCode,
  updatePhoneNumber,
  updateUserLanguage,
  changePassword,
  enable2FA,
  disable2FA,
  getMediaUrl,
} from './user';

// Contact actions
export {
  submitContact,
  createLead,
  getNotices,
  getNotifications,
} from './contact';

// Verification actions
export {
  getVerificationStatus,
  saveStartedInfo,
  checkClientAnswer,
  checkClientProfessionalAnswer,
  getMyReferralCode,
  getReferralInfoByReferralCode,
  savePersonalInfo,
  saveFinancialInfo,
  saveAgreement,
  submitDocument,
  uploadFile,
  uploadChunk,
  mergeChunks,
  uploadVerificationDocument,
} from './verification';

// Trade account actions
export { changeTradeAccountPassword } from './trade-account';

// Payment actions
export {
  getPaymentInfoList,
  deletePaymentInfo,
  createPaymentInfo,
  updatePaymentInfo,
  type PaymentInfo,
} from './payment';

export {
  getAddressList,
  createAddress,
  updateAddress,
  type AddressInfo,
  type AddressContent,
  type AddressPayload,
  type UpdateAddressPayload,
} from './address';

// Account actions
export {
  getLiveAccounts,
  getPendingApplications,
  getDemoAccounts,
  getServiceMap,
  getLiveAccountConfig,
  getDemoAccountConfig,
  createLiveAccount,
  createDemoAccount,
  getAccountLeverageConfig,
  changeLeverage,
  requestPasswordReset,
  getAccountByNumber,
  getAccountTransactions,
  getAccountDeposits,
  getAccountWithdrawals,
  getAccountTrades,
  cancelAccountWithdrawal,
  getDepositGuide,
  getDepositReceiptFiles,
  uploadDepositReceipt,
  updateAccountAlias,
  updateDefaultParentAccount,
} from './accounts';

// Deposit actions
export {
  getDepositGroups,
  getDepositGroupInfo,
  postAccountDeposit,
} from './deposit';

// Eventshop actions
export {
  getEventDetail,
  getEventUserDetail,
  registerEvent,
  getShopCategories,
  getShopItems,
  getShopItemDetail,
  purchaseItem,
  getShopOrderList,
  getOrderDetail,
  confirmDelivery,
  updateOrderAddress,
  getPointsHistory,
  getRewardRebateList,
  getEventList,
  markEventChecked,
} from './eventshop';

// IB actions
export {
  getIBClients,
  getIBReferralHistory,
  getIBViewEmailCode,
  getIBEmailByCode,
  getIBTradeReports,
  getIBAccountTrades,
  getIBAccountTransactions,
  getIBDeposits,
  getIBWithdrawals,
  getIBRebates,
  getIBRebateRuleDetail,
  getIBRebateRuleDetailFull,
  getIBProductCategory,
  getIBDefaultLevelSettingMap,
  getIBAccountsWithConfig,
  getIBRebateRuleRemain,
  getIBRebateRuleByAccount,
  updateIBRebateRule,
  getIBDefaultLevelSetting,
  getIBAccountDefaultLevel,
  getIBRebateDistribution,
  getIBChildStat,
  getIBRebateStatBySymbol,
  getIBLinks,
  getIBLinkDetail,
  getReferralCodeSupplement,
  createIBLink,
  createIBLinkForIB,
  createIBLinkForClient,
  updateIBLink,
  setIBDefaultClient,
  getIBReferralCodes,
  createIBReferralCode,
  updateIBReferralCode,
  getRebateSymbolCategory,
  getSymbolCategory,
  getAllSymbols,
  getIBAgentRules,
  getBrokerRebateRules,
  getIBReportRequests,
  getIBRebateTodayValue,
  getIBRebateTotalValue,
  getIBRebateDailySeries,
  getIBRebateHourlySeries,
  getIBRebateMonthlySeries,
  getIBTradeTodayVolume,
  getIBTradeSymbolVolume,
  getIBLatestDeposits,
  getIBTodayAccountCreation,
  getIBDepositTodayValue,
  createIBMonthlyReport,
} from './ib';

// Sales actions
export {
  getSalesClients,
  getSalesAccountDetail,
  getSalesAccountStat,
  getSalesReferralPath,
  getSalesLevelAccounts,
  getSalesViewEmailCode,
  getSalesEmailByCode,
  getSalesTradeReports,
  getSalesClientTrades,
  getSalesClientTransactions,
  getSalesTransactionReports,
  getSalesDeposits,
  getSalesWithdrawals,
  getSalesLinks,
  getReferralLinkDetail,
  getSalesLinkDetail,
  createSalesLinkForIB,
  createSalesLinkForClient,
  updateSalesLink,
  setSalesDefaultCode,
  getSalesReferralHistory,
  getSalesIBAccountConfig,
  getSalesAccountDefaultLevel,
  getSalesDefaultLevelSetting,
  getSalesAvailableAccountTypes,
  getSalesIBRebateRuleDetail,
  getSalesIBRebateRuleRemain,
  getSalesIBRebateRule,
  updateSalesIBRebateRule,
  updateSalesTopIBRebateRule,
  getSalesAgentRules,
  createSalesIBAgentLink,
  createSalesIBClientLink,
  getSalesLeads,
  getSalesLeadDetail,
  addSalesLeadComment,
  getSalesStatistics,
  getSalesChildStat,
  getSalesIbStat,
  getSalesRebateStatBySymbol,
  salesOpenTradeAccount,
  salesFuzzySearchAccount,
  getSalesSymbolCategory,
  getSalesRebateDirectSymbols,
} from './sales';

// Rep actions
export {
  getRepClients,
  repFuzzySearchAccount,
  getRepViewEmailCode,
  getRepEmailByCode,
  getRepClientTransactions,
  getRepClientTrades,
  getRepTradeReports,
  getRepTransactionReports,
  getRepDeposits,
  getRepWithdrawals,
} from './rep';

// Wallet actions
export {
  getWalletList,
  getPrimaryWallet,
  getWithdrawalTransactions,
  getTransferTransactions,
  getAdjustTransactions,
  getRefundTransactions,
  getRebateTransactions,
  getDownlineRewardTransactions,
  cancelWithdrawal,
  getWalletWithdrawGroups,
  getWalletWithdrawGroupInfo,
  getUserPaymentInfoList,
  createUserPaymentInfo,
  submitWalletWithdrawal,
  getTradeAccounts,
  searchTransferTarget,
  sendTransferVerificationCode,
  transferToTradeAccount,
  transferToWallet,
  transferBetweenTradeAccounts,
} from './wallet';
