apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: general-arm
spec:
  template:
    spec:
      # --- ADD THIS BLOCK ---
      nodeClassRef:
        group: eks.amazonaws.com
        kind: NodeClass
        name: default
      # ----------------------
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["arm64"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand", "spot"]
  weight: 10

