alter table trd."_TradeRebate"
    add "TradeServiceId" integer not null;

alter table trd."_TradeRebate"
    add "Ticket" bigint default 0 not null;

alter table trd."_TradeRebate"
    add "AccountNumber" bigint default 0 not null;

alter table trd."_TradeRebate"
    add "ClosedOn" timestamp with time zone default now() not null;

alter table trd."_TradeRebate"
    drop column "Amount";

alter table trd."_TradeRebate"
    add "OpenedOn" timestamp with time zone default now() not null;

alter table trd."_TradeRebate"
    rename column "SymbolCode" to "Symbol";

-- update trd."_TradeRebate" tr
-- set "TradeServerId"=tt."ServiceId",
--     "Ticket"=tt."Ticket",
--     "AccountNumber"=tt."AccountNumber",
--     "ClosedOn"=tt."ClosedAt"
-- from trd."_TradeTransaction" as tt
-- where tr."TradeId" = tt."Id";

create unique index "_TradeRebate_TradeServiceId_Ticket_uindex"
    on trd."_TradeRebate" ("TradeServiceId", "Ticket");

alter table trd."_TradeRebate"
    add constraint "_TradeRebate__TradeService_Id_fk"
        foreign key ("TradeServiceId") references trd."_TradeService";

alter table trd."_TradeRebate"
    alter column "TradeAccountId" drop not null;
    -- alter table trd."_TradeRebate"
    -- drop column "TradeId";

create index "_TradeRebate_Status_index"
    on trd."_TradeRebate" ("Status");

alter table trd."_TradeRebate"
    add "TimeStamp" bigint default 0 not null;

alter table trd."_TradeRebate"
    add "Action" integer default 0 not null;

create index "_TradeRebate_Action_index"
    on trd."_TradeRebate" ("Action");

create index "_TradeRebate_TimeStamp_index"
    on trd."_TradeRebate" ("TimeStamp");

-- create table trd."_TradeRebate"
-- (
--     "Id"             bigint generated by default as identity (start with 10000)
--         constraint "_TradeRebate_pk"
--             primary key,
--     "TradeAccountId" bigint
--         constraint "_TradeRebate__TradeAccount_Id_fk"
--             references trd."_TradeAccount",
--     "TradeServiceId" integer                  default 0     not null
--         constraint "_TradeRebate__TradeService_Id_fk"
--             references trd."_TradeService",
--     "Ticket"         bigint                   default 0     not null,
--     "AccountNumber"  bigint                   default 0     not null,
--     "CurrencyId"     integer                                not null
--         constraint "_TradeRebate__Currency_Id_fk"
--             references acct."_Currency",
--     "Volume"         integer                  default 0     not null,
--     "Action"         integer                  default 0     not null,
--     "Status"         integer                  default 0     not null,
--     "RuleType"       integer                  default 0     not null,
--     "CreatedOn"      timestamp with time zone default now() not null,
--     "UpdatedOn"      timestamp with time zone default now() not null,
--     "ClosedOn"       timestamp with time zone default now() not null,
--     "OpenedOn"       timestamp with time zone default now() not null,
--     "TimeStamp"      bigint                   default 0     not null,
--     "Symbol"         varchar(20)                            not null
-- );

-- create index "_TradeRebate_TradeAccountId_index"
--     on trd."_TradeRebate" ("TradeAccountId");

-- create index "IX__TradeRebate_CurrencyId"
--     on trd."_TradeRebate" ("CurrencyId");

-- create unique index "_TradeRebate_TradeServiceId_Ticket_uindex"
--     on trd."_TradeRebate" ("TradeServiceId", "Ticket");

-- create index "_TradeRebate_Status_index"
--     on trd."_TradeRebate" ("Status");

-- create index "_TradeRebate_AccountNumber_index"
--     on trd."_TradeRebate" ("AccountNumber");

-- create index "_TradeRebate_Action_index"
--     on trd."_TradeRebate" ("Action");

-- create index "_TradeRebate_TimeStamp_index"
--     on trd."_TradeRebate" ("TimeStamp");



alter table trd."_Rebate"
    add "TradeRebateId" bigint;

-- update trd."_Rebate" tr
-- set "TradeRebateId"=tt."ServiceId",
--     "Ticket"=tt."Ticket"
-- from trd."_TradeTransaction" as tt
-- where tr."TradeId" = tt."Id";

alter table trd."_Rebate"
    add constraint "_Rebate__TradeRebate_Id_fk"
        foreign key ("TradeRebateId") references trd."_TradeRebate";

-- alter table trd."_Rebate"
--     drop column "TradeId";


-- create table trd."_Rebate"
-- (
--     "Id"            bigint  not null
--         constraint rebates_pkey
--             primary key
--         constraint trd_rebates_matter_id_foreign
--             references core."_Matter",
--     "PartyId"       bigint  not null
--         constraint trd_rebates_party_id_foreign
--             references core."_Party",
--     "AccountId"     bigint  not null
--         constraint trd_rebates_account_id_foreign
--             references trd."_Account",
--     "FundType"      integer not null
--         constraint "_Rebate__FundType_Id_fk"
--             references acct."_FundType",
--     "CurrencyId"    integer not null
--         constraint trd_rebates_currency_id_foreign
--             references acct."_Currency",
--     "Amount"        bigint  not null,
--     "TradeRebateId" bigint
--         constraint "_Rebate__TradeRebate_Id_fk"
--             references trd."_TradeRebate",
--     "HoldUntilOn"   timestamp with time zone,
--     "Information"   text    not null
-- );

-- create index "_Rebate_HoldUntilOn_index"
--     on trd."_Rebate" ("HoldUntilOn");

-- create index "IX__Rebate_FundType"
--     on trd."_Rebate" ("FundType");

-- create index trd_rebates_account_id_index
--     on trd."_Rebate" ("AccountId");

-- create index trd_rebates_currency_id_index
--     on trd."_Rebate" ("CurrencyId");

-- create index trd_rebates_party_id_index
--     on trd."_Rebate" ("PartyId");

-- create index "_Rebate_TradeRebateId_index"
--     on trd."_Rebate" ("TradeRebateId");
