-- drop table trd."_AccountGroup";
-- drop table trd."_Group";

create table trd."_Group"
(
    "Id"             bigint generated by default as identity
        constraint "_Group_pk"
            primary key,
    "OwnerAccountId" bigint                                 not null
        constraint "_Group__Account_Id_fk"
            references trd."_Account",
    "Type"           integer                                not null,
    "CreatedOn"      timestamp with time zone default now() not null,
    "UpdatedOn"      timestamp with time zone default now() not null,
    "Name"           varchar(64)                            not null,
    "Description"    varchar(256)                           not null
);

create unique index "_Group_AccountId_Type_uindex"
    on trd."_Group" ("OwnerAccountId", "Type");

create unique index "_Group_Name_uindex"
    on trd."_Group" ("Name");

create table trd."_AccountGroup"
(
    "GroupId"   bigint not null
        constraint "_AccountGroup__Group_Id_fk"
            references trd."_Group",
    "AccountId" bigint not null
        constraint "_AccountGroup__Accounts_Id_fk"
            references trd."_Account",
    constraint "_AccountGroup_pk"
        primary key ("AccountId", "GroupId")
);

create index "IX__AccountGroup_GroupId"
    on trd."_AccountGroup" ("GroupId");

-- ---- seed
-- insert into trd."_Group" ("OwnerAccountId", "Type", "Name", "Description")
-- select "Id", 10, CONCAT('s-', "Code"), "Code"
-- from trd."_Account"
-- where "Role" = 100;

-- insert into trd."_Group" ("OwnerAccountId", "Type", "Name", "Description")
-- select "Id",
--        30,
--        CONCAT('a-', case when length("Code") = 0 then "Id"::text else "Code" end),
--        "Code"
-- from trd."_Account"
-- where "Role" = 300
-- on conflict do nothing;

-- insert into trd."_AccountGroup"("GroupId", "AccountId")
-- select sg."Id", a."Id"
-- from trd."_Account" a
--          join trd."_Group" sg on sg."OwnerAccountId" = a."SalesAccountId" and sg."Type" = 10;

-- insert into trd."_AccountGroup"("GroupId", "AccountId")
-- select sg."Id", a."Id"
-- from trd."_Account" a
--          join trd."_Group" sg on sg."OwnerAccountId" = a."AgentAccountId" and sg."Type" = 30;