drop table if exists trd."_RebateAgentRule";
create table trd."_RebateAgentRule"
(
    "Id"             bigint generated by default as identity
        constraint "_AgentRebateRule_Id_uindex"
            primary key,
    "ParentId"       bigint
        constraint "_RebateAgentRule__RebateAgentRule_Id_fk"
            references trd."_RebateAgentRule",
    "AgentAccountId" bigint                                 not null
        constraint "_AgentRebateRule__Account_Id_fk"
            references trd."_Account",
    "Schema"         json                     default '[]'  not null,
    "CreatedOn"      timestamp with time zone default now() not null,
    "UpdatedOn"      timestamp with time zone default now() not null
);

create unique index "_AgentRebateRule_AgentAccountId_uindex"
    on trd."_RebateAgentRule" ("AgentAccountId");

alter table trd."_RebateClientRule"
    add "RebateDirectSchemaId" bigint;

alter table trd."_RebateClientRule"
    add constraint "_RebateClientRule__RebateDirectSchema_Id_fk"
        foreign key ("RebateDirectSchemaId") references trd."_RebateDirectSchema";