drop table if exists trd."_RebatePipFormula";
-- drop table if exists trd."_DirectRebateRule";
-- drop table if exists trd."_RebateRuleItem";
-- drop table if exists trd."_RebateRule";

create table trd."_RebateRule"
(
    "Id"          bigint generated by default as identity
        constraint "_RebateRule_pk"
            primary key,
    "CreatedBy"   bigint                                                 not null
        constraint "_RebateRule__Party_Id_fk2"
            references core."_Party",
    "CreatedOn"   timestamp with time zone default now()                 not null,
    "ConfirmedBy" bigint
        constraint "_RebateRule__Party_Id_fk"
            references core."_Party",
    "ConfirmedOn" timestamp with time zone,
    "UpdatedOn"   timestamp with time zone default now()                 not null,
    "Name"        varchar(64)              default ''::character varying not null,
    "Note"        varchar(256)             default ''::character varying not null
);

create index "IX__RebateRule_CreatedBy"
    on trd."_RebateRule" ("CreatedBy");

create unique index "_RebateRule_Name_uindex"
    on trd."_RebateRule" ("Name");

create table trd."_RebateRuleItem"
(
    "Id"           bigint generated by default as identity
        constraint "_RebateRuleItem_pk"
            primary key,
    "RebateRuleId" bigint                                 not null
        constraint "_RebateRuleItem__RebateRule_Id_fk"
            references trd."_RebateRule"
            on delete cascade,
    "Rate"         numeric(16, 2)                         not null,
    "Pips"         numeric(16, 2)                         not null,
    "Commission"   numeric(16, 2)                         not null,
    "CreatedOn"    timestamp with time zone default now() not null,
    "UpdatedOn"    timestamp with time zone default now() not null,
    "SymbolCode"   varchar(64)                            not null
);

create index "_RebateRuleItem_SymbolCode_index"
    on trd."_RebateRuleItem" ("SymbolCode");

create unique index "_RebateRuleItem_SymbolCode_RebateRuleId_uindex"
    on trd."_RebateRuleItem" ("SymbolCode", "RebateRuleId");

create index "IX__RebateRuleItem_RebateRuleId"
    on trd."_RebateRuleItem" ("RebateRuleId");

create table trd."_RebateRuleTemplate"
(
    "Id"        bigint generated by default as identity
        constraint "_RebateRuleTemplate_pk"
            primary key,
    "CreatedBy" bigint                                                 not null
        constraint "_RebateRuleTemplate__Party_Id_fk2"
            references core."_Party",
    "CreatedOn" timestamp with time zone default now()                 not null,
    "UpdatedOn" timestamp with time zone default now()                 not null,
    "Name"      varchar(64)              default ''::character varying not null,
    "Note"      varchar(256)             default ''::character varying not null
);

create index "IX__RebateRuleTemplate_CreatedBy"
    on trd."_RebateRuleTemplate" ("CreatedBy");

create table trd."_RebateRuleTemplateItem"
(
    "Id"           bigint generated by default as identity
        constraint "_RebateRuleTemplateItem_pk"
            primary key,
    "RebateRuleId" bigint                                 not null
        constraint "_RebateRuleTemplateItem__RebateRule_Id_fk"
            references trd."_RebateRuleTemplate"
            on delete cascade,
    "Rate"         numeric(16, 2)                         not null,
    "Pips"         numeric(16, 2)                         not null,
    "Commission"   numeric(16, 2)                         not null,
    "CreatedOn"    timestamp with time zone default now() not null,
    "UpdatedOn"    timestamp with time zone default now() not null,
    "SymbolCode"   varchar(64)                            not null
);

create index "_RebateRuleTemplateItem_SymbolCode_index"
    on trd."_RebateRuleTemplateItem" ("SymbolCode");

create unique index "_RebateRuleTemplateItem_SymbolCode_RebateRuleId_uindex"
    on trd."_RebateRuleTemplateItem" ("SymbolCode", "RebateRuleId");

create index "IX__RebateRuleTemplateItem_RebateRuleId"
    on trd."_RebateRuleTemplateItem" ("RebateRuleId");

create table trd."_DirectRebateRule"
(
    "Id"                   bigint generated by default as identity
        constraint "_DirectRebateRule_pk"
            primary key,
    "SourceTradeAccountId" bigint                                 not null
        constraint "_DirectRebateRule__Account_Id_fk"
            references trd."_TradeAccount",
    "TargetAccountId"      bigint                                 not null
        constraint "_DirectRebateRule__Account_Id_fk2"
            references trd."_Account",
    "RebateRuleId"         bigint                                 not null
        constraint "_DirectRebateRule__RebateRule_Id_fk"
            references trd."_RebateRule",
    "CreatedOn"            timestamp with time zone default now() not null,
    "CreatedBy"            bigint                                 not null
        constraint "_DirectRebateRule_CreatedBy_Party_Id_fk"
            references core."_Party",
    "ConfirmedBy"          bigint
        constraint "_DirectRebateRule_ConfirmedBy_Party_Id_fk"
            references core."_Party",
    "ConfirmedOn"          timestamp with time zone,
    "UpdatedOn"            timestamp with time zone default now() not null,
    constraint "_DirectRebateRule_Source_Target_pk"
        unique ("TargetAccountId", "SourceTradeAccountId")
);

create index "IX__DirectRebateRule_SourceAccountId"
    on trd."_DirectRebateRule" ("SourceTradeAccountId");

create table trd."_RebateRuleTemplateBundle"
(
    "Id"        bigint                                                 not null
        constraint "_RebateRuleTemplateBundle_pk"
            primary key,
    "Type"      integer                  default 0                     not null,
    "CreatedBy" bigint                                                 not null
        constraint "_RebateRuleTemplateBundle__Party_Id_fk"
            references core."_Party",
    "CreatedOn" timestamp with time zone default now()                 not null,
    "UpdatedOn" timestamp with time zone default now()                 not null,
    "Name"      varchar(64)                                            not null,
    "Note"      varchar(256)             default ''::character varying not null,
    "Data"      jsonb                    default '[]'::jsonb           not null
);

create unique index "_RebateRuleTemplateBundle_Name_uindex"
    on trd."_RebateRuleTemplateBundle" ("Name");

