create table trd."_Lead"
(
    "Id"          bigint generated by default as identity
        constraint "_Lead_pk"
            primary key,
    "PartyId"     bigint,
    "SourceType"  integer                  default 0                     not null,
    "Status"      integer                                                not null,
    "IsArchived"  integer                  default 0                     not null,
    "CreatedOn"   timestamp with time zone default now()                 not null,
    "UpdatedOn"   timestamp with time zone default now()                 not null,
    "Name"        varchar(256)             default ''::character varying not null,
    "Email"       varchar(256)             default ''::character varying not null,
    "PhoneNumber" varchar(64)              default ''::character varying not null,
    "Supplement"  json                     default '{}'::json            not null
);

create index "_Lead_CreatedOn_index"
    on trd."_Lead" ("CreatedOn");

create index "_Lead_Email_index"
    on trd."_Lead" ("Email");

create index "_Lead_PhoneNumber_index"
    on trd."_Lead" ("PhoneNumber");

create table trd."_LeadOwnerAccount"
(
    "LeadId"    bigint not null
        constraint "_LeadOwnerAccount__Lead_Id_fk"
            references trd."_Lead"
            on delete cascade,
    "AccountId" bigint not null
        constraint "_LeadOwnerAccount__Account_Id_fk"
            references trd."_Account"
            on delete cascade,
    constraint "_LeadOwnerAccount_pk"
        primary key ("LeadId", "AccountId")
);

create index "IX__LeadOwnerAccount_AccountId"
    on trd."_LeadOwnerAccount" ("AccountId");
