create table "_Role"
(
    "Id"               bigint generated by default as identity
        constraint "PK__Role"
            primary key,
    "Name"             varchar(256),
    "NormalizedName"   varchar(256),
    "ConcurrencyStamp" text
);

alter table "_Role"
    owner to bcrpro;

create unique index "RoleNameIndex"
    on "_Role" ("NormalizedName");

grant select on "_Role" to dev_read;

INSERT INTO auth."_Role" ("Id", "Name", "NormalizedName", "ConcurrencyStamp") VALUES (1000, 'Guest', 'GUEST', 'b6fd814d-888c-480a-be2e-f804303ac0fd');
INSERT INTO auth."_Role" ("Id", "Name", "NormalizedName", "ConcurrencyStamp") VALUES (510, 'MLM', 'MLM', '8c1e9daa-f6a2-43e6-b2a6-91d4a075aedf');
INSERT INTO auth."_Role" ("Id", "Name", "NormalizedName", "ConcurrencyStamp") VALUES (502, 'EventShopTest', 'EVENTSHOPTEST', 'a88582db-1bf2-490d-bada-1312ea369323');
INSERT INTO auth."_Role" ("Id", "Name", "NormalizedName", "ConcurrencyStamp") VALUES (501, 'EventShop', 'EVENTSHOP', 'a88582db-1bf2-490d-bada-1312ea369322');
INSERT INTO auth."_Role" ("Id", "Name", "NormalizedName", "ConcurrencyStamp") VALUES (400, 'Client', 'CLIENT', '5e7732ef-9550-403f-9328-f8ecc04165ff');
INSERT INTO auth."_Role" ("Id", "Name", "NormalizedName", "ConcurrencyStamp") VALUES (310, 'Wholesale', 'WHOLESALE', 'feb306cd-75c8-433a-aaaf-20f982daed80');
INSERT INTO auth."_Role" ("Id", "Name", "NormalizedName", "ConcurrencyStamp") VALUES (300, 'IB', 'IB', '8869867c-29db-40c3-b9cd-08f4baf5d188');
INSERT INTO auth."_Role" ("Id", "Name", "NormalizedName", "ConcurrencyStamp") VALUES (200, 'Broker', 'BROKER', '3f97a5ff-7acf-41d2-b38c-d86fe370c34f');
INSERT INTO auth."_Role" ("Id", "Name", "NormalizedName", "ConcurrencyStamp") VALUES (110, 'Rep', 'REP', '7cd819b2-a8c7-470b-b6ef-92d487281cd5');
INSERT INTO auth."_Role" ("Id", "Name", "NormalizedName", "ConcurrencyStamp") VALUES (100, 'Sales', 'SALES', '0430cf2a-2f54-447d-a627-0ead1f5a506e');
INSERT INTO auth."_Role" ("Id", "Name", "NormalizedName", "ConcurrencyStamp") VALUES (99, 'Admin', 'ADMIN', null);
INSERT INTO auth."_Role" ("Id", "Name", "NormalizedName", "ConcurrencyStamp") VALUES (90, 'BaseAdmin', 'BASEADMIN', null);
INSERT INTO auth."_Role" ("Id", "Name", "NormalizedName", "ConcurrencyStamp") VALUES (81, 'JpAdmin', 'JPADMIN', 'a88582db-1bf2-490d-bada-1312ea369324');
INSERT INTO auth."_Role" ("Id", "Name", "NormalizedName", "ConcurrencyStamp") VALUES (80, 'CustomerService', 'CUSTOMERSERVICE', null);
INSERT INTO auth."_Role" ("Id", "Name", "NormalizedName", "ConcurrencyStamp") VALUES (70, 'CaseAdmin', 'CASEADMIN', 'b6fd814d-888c-480a-be2e-f804303ac0fh');
INSERT INTO auth."_Role" ("Id", "Name", "NormalizedName", "ConcurrencyStamp") VALUES (60, 'EventAdmin', 'EVENTADMIN', 'a88582db-1bf2-490d-bada-1312ea369324');
INSERT INTO auth."_Role" ("Id", "Name", "NormalizedName", "ConcurrencyStamp") VALUES (50, 'FundingAdmin', 'FUNDINGADMIN', null);
INSERT INTO auth."_Role" ("Id", "Name", "NormalizedName", "ConcurrencyStamp") VALUES (40, 'AccountAdmin', 'ACCOUNTADMIN', 'feb306cd-75c8-433a-eaaf-20f982daed80');
INSERT INTO auth."_Role" ("Id", "Name", "NormalizedName", "ConcurrencyStamp") VALUES (30, 'DepositAdmin', 'DEPOSIT', '7849837c-20db-45c3-b8cd-01f4baf2d118');
INSERT INTO auth."_Role" ("Id", "Name", "NormalizedName", "ConcurrencyStamp") VALUES (21, 'KycOfficer', 'KYCOFFICER', 'a88582db-1bf2-490d-bada-1312ea369321');
INSERT INTO auth."_Role" ("Id", "Name", "NormalizedName", "ConcurrencyStamp") VALUES (20, 'Compliance', 'COMPLIANCE', 'a88582db-1bf2-490d-bada-1312ea369320');
INSERT INTO auth."_Role" ("Id", "Name", "NormalizedName", "ConcurrencyStamp") VALUES (16, 'ShowContact', 'ShowContact', 'a88582db-1bf2-490d-cdcd-1312ea369532');
INSERT INTO auth."_Role" ("Id", "Name", "NormalizedName", "ConcurrencyStamp") VALUES (15, 'Dealing', 'DEALING', 'a88582db-1bf2-490d-bada-1312ea369532');
INSERT INTO auth."_Role" ("Id", "Name", "NormalizedName", "ConcurrencyStamp") VALUES (13, 'DemoAuAdmin', 'DEMOAUADMIN', '5FC62000-196A-10CB-8225-A3C21F573EFC');
INSERT INTO auth."_Role" ("Id", "Name", "NormalizedName", "ConcurrencyStamp") VALUES (12, 'Supervisor', 'SUPERVISOR', '5FC62000-196A-10CB-8215-A3C21F573EFA');
INSERT INTO auth."_Role" ("Id", "Name", "NormalizedName", "ConcurrencyStamp") VALUES (10, 'TenantAdmin', 'TENANTADMIN', 'fc79facc-5845-42e4-9723-c6c367d6d23e');
INSERT INTO auth."_Role" ("Id", "Name", "NormalizedName", "ConcurrencyStamp") VALUES (2, 'SuperAdmin', 'SUPERADMIN', '8c1e9daa-f6a2-43e6-b2a6-91d4a075ae9f');
