create table "_CentralConfig"
(
    "Id"          bigint generated by default as identity
        constraint "_CentralConfig_pk"
            primary key,
    "RowId"       bigint                                 not null,
    "DataFormat"  text                                   not null,
    "Value"       text                                   not null,
    "Category"    text                                   not null,
    "Key"         text                                   not null,
    "Description" text                                   not null,
    "CreatedOn"   timestamp with time zone default now() not null,
    "UpdatedOn"   timestamp with time zone default now() not null,
    "UpdatedBy"   bigint                                 not null,
    "Name"        varchar(32)                            not null
);

alter table "_CentralConfig"
    owner to bcrpro;

create index "IX__CentralConfig_Category"
    on "_CentralConfig" ("Category");

create index "IX__CentralConfig_DataFormat"
    on "_CentralConfig" ("DataFormat");

create index "IX__CentralConfig_Key"
    on "_CentralConfig" ("Key");

create index "IX__CentralConfig_RowId"
    on "_CentralConfig" ("RowId");

INSERT INTO core."_CentralConfig" ("Id", "RowId", "DataFormat", "Value", "Category", "Key", "Description", "CreatedOn", "UpdatedOn", "UpdatedBy", "Name") VALUES (1, 0, 'json', e'{
  "siteId": 1,
  "tenantId": 10000,
  "ver": "1.0.14",
  "android": "https://play.google.com/store/apps/details?id=com.bacera.bcr",
  "ios": "https://apps.apple.com/app/bcr-trader/id6740502137",
  "apk": "https://bcrpropublic.s3.ap-southeast-1.amazonaws.com/android/bcr_trader_1_0_14_1.apk",
  "forceUpdate": false,
  "welcome": [{
    "title": {
      "zh-cn": "欢迎使用 BCR",
      "zh-hk": "歡迎使用 BCR",
      "zh-tw": "歡迎使用 BCR",
      "en-us": "Welcome to BCR",
      "vi-vn": "Chào mừng bạn đến với BCR",
      "th-th": "ยินดีต้อนรับสู่ BCR",
      "mn-mn": "BCR-д тавтай морилно уу",
      "jp-jp": "BCRへようこそ",
      "ms-my": "Selamat datang ke BCR",
      "id-id": "Selamat datang di BCR"
    },
    "content": {
      "zh-cn": "",
      "zh-hk": "",
      "zh-tw": "",
      "en-us": "",
      "vi-vn": "",
      "th-th": "",
      "mn-mn": "",
      "jp-jp": "",
      "ms-my": "",
      "id-id": ""
    },
    "pic":
        "https://bcrpropublic.s3.ap-southeast-1.amazonaws.com/app2.png"
  }]
}', 'Public', 'WelcomeInfo', 'Welcome Info', '2025-01-15 19:16:11.725922 +00:00', '2025-01-15 19:16:11.725922 +00:00', 0, 'Welcome Info');
INSERT INTO core."_CentralConfig" ("Id", "RowId", "DataFormat", "Value", "Category", "Key", "Description", "CreatedOn", "UpdatedOn", "UpdatedBy", "Name") VALUES (2, 0, 'json', e'["https://cfds3.chnthebcr.com/api",
            "https://cfds1.chnthebcr.com/api",
            "https://cfds2.chnthebcr.com/api",
            "https://cfds4.chnthebcr.com/api",
            "https://cfds5.chnthebcr.com/api",
            "https://thebcr.com/api",
            "https://thebcrsea.com/api",
            "https://api.thebcrsea.com/api",
            "https://thegoodluckbeauty.com"]', 'Public', 'ApiDomain', 'ApiDomain', '2025-01-28 01:34:53.456120 +00:00', '2025-01-28 01:34:53.456120 +00:00', 0, 'ApiDomain');
