create table "_RebateDirectSchemaItem"
(
    "Id"                   bigint generated by default as identity
        constraint "_RebateDirectSchemaItem_pk"
            primary key,
    "RebateDirectSchemaId" bigint                                 not null
        constraint "_RebateDirectSchemaItem__RebateDirectSchema_Id_fk"
            references "_RebateDirectSchema"
            on delete cascade,
    "Rate"                 numeric(16, 2)                         not null,
    "Pips"                 numeric(16, 2)                         not null,
    "Commission"           numeric(16, 2)                         not null,
    "CreatedOn"            timestamp with time zone default now() not null,
    "UpdatedOn"            timestamp with time zone default now() not null,
    "SymbolCode"           varchar(64)                            not null
);

alter table "_RebateDirectSchemaItem"
    owner to bcrpro;

create index "_RebateDirectSchemaItem_RebateRuleId_index"
    on "_RebateDirectSchemaItem" ("RebateDirectSchemaId");

create index "_RebateDirectSchemaItem_SymbolCode_index"
    on "_RebateDirectSchemaItem" ("SymbolCode");

grant select on "_RebateDirectSchemaItem" to dev_read;



INSERT INTO trd."_RebateDirectSchemaItem" ("Id", "RebateDirectSchemaId", "Rate", "Pips", "Commission", "CreatedOn", "UpdatedOn", "SymbolCode") VALUES (1, 6, 2.00, 1.00, 10.00, '1970-01-01 00:00:00.000000 +00:00', '1970-01-01 00:00:00.000000 +00:00', 'DEMO_#AAPL');