-- auto-generated definition
create table "_Currency"
(
    "Id"     integer     not null
        constraint currencies_pkey
            primary key,
    "Code"   char(3)     not null,
    "Name"   varchar(50) not null,
    "Entity" varchar(64) not null
);

alter table "_Currency"
    owner to bcrpro;

create unique index acct_currencies_code_unique
    on "_Currency" ("Code");

grant select on "_Currency" to dev_read;

INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (-1, 'N/A', 'Invalid', 'Invalid');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (8, 'ALL', 'Lek', 'ALBANIA');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (12, 'DZD', 'Algerian Dinar', 'ALGERIA');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (32, 'ARS', 'Argentine Peso', 'ARGENTINA');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (36, 'AUD', 'Australian Dollar', 'AUSTRALIA');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (44, 'BSD', 'Bahamian Dollar', 'BAHAMAS (THE)');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (48, 'BHD', 'Bahraini Dinar', 'BAHRAIN');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (50, 'BDT', 'Taka', 'BANGLADESH');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (51, 'AMD', 'Armenian Dram', 'ARMENIA');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (52, 'BBD', 'Barbados Dollar', 'BARBADOS');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (60, 'BMD', 'Bermudian Dollar', 'BERMUDA');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (64, 'BTN', 'Ngultrum', 'BHUTAN');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (68, 'BOB', 'Boliviano', 'BOLIVIA (PLURINATIONAL STATE OF)');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (72, 'BWP', 'Pula', 'BOTSWANA');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (84, 'BZD', 'Belize Dollar', 'BELIZE');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (90, 'SBD', 'Solomon Islands Dollar', 'SOLOMON ISLANDS');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (96, 'BND', 'Brunei Dollar', 'BRUNEI DARUSSALAM');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (104, 'MMK', 'Kyat', 'MYANMAR');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (108, 'BIF', 'Burundi Franc', 'BURUNDI');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (116, 'KHR', 'Riel', 'CAMBODIA');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (124, 'CAD', 'Canadian Dollar', 'CANADA');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (132, 'CVE', 'Cabo Verde Escudo', 'CABO VERDE');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (136, 'KYD', 'Cayman Islands Dollar', 'CAYMAN ISLANDS (THE)');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (144, 'LKR', 'Sri Lanka Rupee', 'SRI LANKA');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (152, 'CLP', 'Chilean Peso', 'CHILE');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (156, 'CNY', 'Yuan Renminbi', 'CHINA');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (170, 'COP', 'Colombian Peso', 'COLOMBIA');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (174, 'KMF', 'Comorian Franc', 'COMOROS (THE)');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (188, 'CRC', 'Costa Rican Colon', 'COSTA RICA');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (191, 'HRK', 'Kuna', 'CROATIA');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (192, 'CUP', 'Cuban Peso', 'CUBA');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (203, 'CZK', 'Czech Koruna', 'CZECHIA');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (208, 'DKK', 'Danish Krone', 'DENMARK');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (214, 'DOP', 'Dominican Peso', 'DOMINICAN REPUBLIC (THE)');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (222, 'SVC', 'El Salvador Colon', 'EL SALVADOR');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (230, 'ETB', 'Ethiopian Birr', 'ETHIOPIA');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (232, 'ERN', 'Nakfa', 'ERITREA');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (238, 'FKP', 'Falkland Islands Pound', 'FALKLAND ISLANDS (THE) [MALVINAS]');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (242, 'FJD', 'Fiji Dollar', 'FIJI');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (262, 'DJF', 'Djibouti Franc', 'DJIBOUTI');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (270, 'GMD', 'Dalasi', 'GAMBIA (THE)');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (292, 'GIP', 'Gibraltar Pound', 'GIBRALTAR');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (320, 'GTQ', 'Quetzal', 'GUATEMALA');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (324, 'GNF', 'Guinean Franc', 'GUINEA');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (328, 'GYD', 'Guyana Dollar', 'GUYANA');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (332, 'HTG', 'Gourde', 'HAITI');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (340, 'HNL', 'Lempira', 'HONDURAS');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (344, 'HKD', 'Hong Kong Dollar', 'HONG KONG');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (348, 'HUF', 'Forint', 'HUNGARY');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (352, 'ISK', 'Iceland Krona', 'ICELAND');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (356, 'INR', 'Indian Rupee', 'INDIA');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (360, 'IDR', 'Rupiah', 'INDONESIA');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (364, 'IRR', 'Iranian Rial', 'IRAN (ISLAMIC REPUBLIC OF)');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (368, 'IQD', 'Iraqi Dinar', 'IRAQ');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (376, 'ILS', 'New Israeli Sheqel', 'ISRAEL');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (388, 'JMD', 'Jamaican Dollar', 'JAMAICA');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (392, 'JPY', 'Yen', 'JAPAN');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (398, 'KZT', 'Tenge', 'KAZAKHSTAN');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (400, 'JOD', 'Jordanian Dinar', 'JORDAN');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (404, 'KES', 'Kenyan Shilling', 'KENYA');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (408, 'KPW', 'North Korean Won', 'KOREA (THE DEMOCRATIC PEOPLE''S REPUBLIC OF)');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (410, 'KRW', 'Won', 'KOREA (THE REPUBLIC OF)');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (414, 'KWD', 'Kuwaiti Dinar', 'KUWAIT');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (417, 'KGS', 'Som', 'KYRGYZSTAN');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (418, 'LAK', 'Lao Kip', 'LAO PEOPLE''S DEMOCRATIC REPUBLIC (THE)');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (422, 'LBP', 'Lebanese Pound', 'LEBANON');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (426, 'LSL', 'Loti', 'LESOTHO');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (430, 'LRD', 'Liberian Dollar', 'LIBERIA');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (434, 'LYD', 'Libyan Dinar', 'LIBYA');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (446, 'MOP', 'Pataca', 'MACAO');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (454, 'MWK', 'Malawi Kwacha', 'MALAWI');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (458, 'MYR', 'Malaysian Ringgit', 'MALAYSIA');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (462, 'MVR', 'Rufiyaa', 'MALDIVES');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (480, 'MUR', 'Mauritius Rupee', 'MAURITIUS');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (484, 'MXN', 'Mexican Peso', 'MEXICO');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (496, 'MNT', 'Tugrik', 'MONGOLIA');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (498, 'MDL', 'Moldovan Leu', 'MOLDOVA (THE REPUBLIC OF)');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (504, 'MAD', 'Moroccan Dirham', 'MOROCCO');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (512, 'OMR', 'Rial Omani', 'OMAN');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (516, 'NAD', 'Namibia Dollar', 'NAMIBIA');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (524, 'NPR', 'Nepalese Rupee', 'NEPAL');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (532, 'ANG', 'Netherlands Antillean Guilder', 'CURAÇAO');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (533, 'AWG', 'Aruban Florin', 'ARUBA');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (548, 'VUV', 'Vatu', 'VANUATU');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (554, 'NZD', 'New Zealand Dollar', 'NEW ZEALAND');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (558, 'NIO', 'Cordoba Oro', 'NICARAGUA');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (566, 'NGN', 'Naira', 'NIGERIA');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (578, 'NOK', 'Norwegian Krone', 'NORWAY');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (586, 'PKR', 'Pakistan Rupee', 'PAKISTAN');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (590, 'PAB', 'Balboa', 'PANAMA');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (598, 'PGK', 'Kina', 'PAPUA NEW GUINEA');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (600, 'PYG', 'Guarani', 'PARAGUAY');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (604, 'PEN', 'Sol', 'PERU');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (608, 'PHP', 'Philippine Peso', 'PHILIPPINES (THE)');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (634, 'QAR', 'Qatari Rial', 'QATAR');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (643, 'RUB', 'Russian Ruble', 'RUSSIAN FEDERATION (THE)');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (646, 'RWF', 'Rwanda Franc', 'RWANDA');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (654, 'SHP', 'Saint Helena Pound', 'SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (682, 'SAR', 'Saudi Riyal', 'SAUDI ARABIA');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (690, 'SCR', 'Seychelles Rupee', 'SEYCHELLES');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (694, 'SLL', 'Leone', 'SIERRA LEONE');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (702, 'SGD', 'Singapore Dollar', 'SINGAPORE');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (704, 'VND', 'Dong', 'VIET NAM');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (706, 'SOS', 'Somali Shilling', 'SOMALIA');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (710, 'ZAR', 'Rand', 'NAMIBIA');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (728, 'SSP', 'South Sudanese Pound', 'SOUTH SUDAN');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (748, 'SZL', 'Lilangeni', 'ESWATINI');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (752, 'SEK', 'Swedish Krona', 'SWEDEN');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (756, 'CHF', 'Swiss Franc', 'SWITZERLAND');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (760, 'SYP', 'Syrian Pound', 'SYRIAN ARAB REPUBLIC');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (764, 'THB', 'Baht', 'THAILAND');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (776, 'TOP', 'Pa''anga', 'TONGA');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (780, 'TTD', 'Trinidad and Tobago Dollar', 'TRINIDAD AND TOBAGO');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (784, 'AED', 'UAE Dirham', 'UNITED ARAB EMIRATES (THE)');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (788, 'TND', 'Tunisian Dinar', 'TUNISIA');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (800, 'UGX', 'Uganda Shilling', 'UGANDA');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (807, 'MKD', 'Denar', 'NORTH MACEDONIA');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (818, 'EGP', 'Egyptian Pound', 'EGYPT');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (826, 'GBP', 'Pound Sterling', 'GUERNSEY');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (834, 'TZS', 'Tanzanian Shilling', 'TANZANIA, UNITED REPUBLIC OF');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (840, 'USD', 'US Dollar', 'UNITED STATES OF AMERICA (THE)');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (841, 'USC', 'US Cent', 'UNITED STATES OF AMERICA (THE)');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (858, 'UYU', 'Peso Uruguayo', 'URUGUAY');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (860, 'UZS', 'Uzbekistan Sum', 'UZBEKISTAN');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (882, 'WST', 'Tala', 'SAMOA');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (886, 'YER', 'Yemeni Rial', 'YEMEN');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (901, 'TWD', 'New Taiwan Dollar', 'TAIWAN (PROVINCE OF CHINA)');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (927, 'UYW', 'Unidad Previsional', 'URUGUAY');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (928, 'VES', 'Bolívar Soberano', 'VENEZUELA (BOLIVARIAN REPUBLIC OF)');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (929, 'MRU', 'Ouguiya', 'MAURITANIA');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (930, 'STN', 'Dobra', 'SAO TOME AND PRINCIPE');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (931, 'CUC', 'Peso Convertible', 'CUBA');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (932, 'ZWL', 'Zimbabwe Dollar', 'ZIMBABWE');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (933, 'BYN', 'Belarusian Ruble', 'BELARUS');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (934, 'TMT', 'Turkmenistan New Manat', 'TURKMENISTAN');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (936, 'GHS', 'Ghana Cedi', 'GHANA');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (938, 'SDG', 'Sudanese Pound', 'SUDAN (THE)');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (940, 'UYI', 'Uruguay Peso en Unidades Indexadas (UI)', 'URUGUAY');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (941, 'RSD', 'Serbian Dinar', 'SERBIA');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (943, 'MZN', 'Mozambique Metical', 'MOZAMBIQUE');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (944, 'AZN', 'Azerbaijan Manat', 'AZERBAIJAN');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (946, 'RON', 'Romanian Leu', 'ROMANIA');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (947, 'CHE', 'WIR Euro', 'SWITZERLAND');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (948, 'CHW', 'WIR Franc', 'SWITZERLAND');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (949, 'TRY', 'Turkish Lira', 'TURKEY');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (950, 'XAF', 'CFA Franc BEAC', 'CAMEROON');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (951, 'XCD', 'East Caribbean Dollar', 'DOMINICA');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (952, 'XOF', 'CFA Franc BCEAO', 'MALI');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (953, 'XPF', 'CFP Franc', 'FRENCH POLYNESIA');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (967, 'ZMW', 'Zambian Kwacha', 'ZAMBIA');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (968, 'SRD', 'Surinam Dollar', 'SURINAME');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (969, 'MGA', 'Malagasy Ariary', 'MADAGASCAR');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (970, 'COU', 'Unidad de Valor Real', 'COLOMBIA');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (971, 'AFN', 'Afghani', 'AFGHANISTAN');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (972, 'TJS', 'Somoni', 'TAJIKISTAN');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (973, 'AOA', 'Kwanza', 'ANGOLA');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (975, 'BGN', 'Bulgarian Lev', 'BULGARIA');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (976, 'CDF', 'Congolese Franc', 'CONGO (THE DEMOCRATIC REPUBLIC OF THE)');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (977, 'BAM', 'Convertible Mark', 'BOSNIA AND HERZEGOVINA');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (978, 'EUR', 'Euro', 'EUROPEAN UNION');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (979, 'MXV', 'Mexican Unidad de Inversion (UDI)', 'MEXICO');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (980, 'UAH', 'Hryvnia', 'UKRAINE');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (981, 'GEL', 'Lari', 'GEORGIA');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (984, 'BOV', 'Mvdol', 'BOLIVIA (PLURINATIONAL STATE OF)');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (985, 'PLN', 'Zloty', 'POLAND');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (986, 'BRL', 'Brazilian Real', 'BRAZIL');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (990, 'CLF', 'Unidad de Fomento', 'CHILE');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (997, 'USN', 'US Dollar (Next day)', 'UNITED STATES OF AMERICA (THE)');
INSERT INTO acct."_Currency" ("Id", "Code", "Name", "Entity") VALUES (999, 'PTS', 'Point', 'Points');
