create table "_RebateDirectSchema"
(
    "Id"          bigint generated by default as identity
        constraint "_RebateDirectSchema_pk"
            primary key,
    "CreatedBy"   bigint                                                 not null
        constraint "_RebateDirectSchema__Party_Id_fk2"
            references core."_Party",
    "CreatedOn"   timestamp with time zone default now()                 not null,
    "ConfirmedBy" bigint
        constraint "_RebateDirectSchema__Party_Id_fk"
            references core."_Party",
    "ConfirmedOn" timestamp with time zone,
    "UpdatedOn"   timestamp with time zone default now()                 not null,
    "Name"        varchar(64)              default ''::character varying not null,
    "Note"        varchar(256)             default ''::character varying not null
);

alter table "_RebateDirectSchema"
    owner to bcrpro;

create index "_RebateDirectSchema_ConfirmedBy_index"
    on "_RebateDirectSchema" ("ConfirmedBy");

create index "_RebateDirectSchema_CreatedBy_index"
    on "_RebateDirectSchema" ("CreatedBy");

create unique index "_RebateDirectSchema_Name_uindex"
    on "_RebateDirectSchema" ("Name");

grant select on "_RebateDirectSchema" to dev_read;

INSERT INTO trd."_RebateDirectSchema" ("Id", "CreatedBy", "CreatedOn", "ConfirmedBy", "ConfirmedOn", "UpdatedOn", "Name", "Note") VALUES (6, 1, '2017-09-07 14:09:14.000000 +00:00', null, null, '2019-08-02 09:24:08.000000 +00:00', 'DEMO_UB_STN', 'Demo data');