-- auto-generated definition
create table "_ExchangeRate"
(
    "Id"             bigint generated by default as identity
        constraint "_ExchangeRate_pk"
            primary key,
    "FromCurrencyId" integer                                                not null
        constraint "_ExchangeRate__Currency_Id_fk"
            references acct."_Currency",
    "ToCurrencyId"   integer                                                not null
        constraint "_ExchangeRate__Currency_Id_fk2"
            references acct."_Currency",
    "BuyingRate"     numeric(16, 8)                                         not null,
    "SellingRate"    numeric(16, 8)                                         not null,
    "AdjustRate"     numeric(16, 8)                                         not null,
    "UpdatedOn"      timestamp with time zone default now()                 not null,
    "CreatedOn"      timestamp with time zone default now()                 not null,
    "Name"           varchar(64)              default ''::character varying not null
);

alter table "_ExchangeRate"
    owner to bcrpro;

create unique index "_ExchangeRate_From_To_ux"
    on "_ExchangeRate" ("FromCurrencyId", "ToCurrencyId");

create index "_ExchangeRate_FromCurrencyId_index"
    on "_ExchangeRate" ("FromCurrencyId");

create unique index "_ExchangeRate_FromCurrencyId_ToCurrencyId_uindex"
    on "_ExchangeRate" ("FromCurrencyId", "ToCurrencyId");

create unique index "_ExchangeRate_Name_uindex"
    on "_ExchangeRate" ("Name");

create index "_ExchangeRate_ToCurrencyId_index"
    on "_ExchangeRate" ("ToCurrencyId");

grant select on "_ExchangeRate" to dev_read;

INSERT INTO trd."_ExchangeRate" ("Id", "FromCurrencyId", "ToCurrencyId", "BuyingRate", "SellingRate", "AdjustRate", "UpdatedOn", "CreatedOn", "Name") VALUES (1, 840, 36, 0.63700000, 0.64590000, 0.00000000, '2025-04-30 04:43:55.513177 +00:00', '2023-11-10 05:15:55.253907 +00:00', 'USDAUD');
INSERT INTO trd."_ExchangeRate" ("Id", "FromCurrencyId", "ToCurrencyId", "BuyingRate", "SellingRate", "AdjustRate", "UpdatedOn", "CreatedOn", "Name") VALUES (4, 36, 156, 4.62830000, 4.66510000, 1.00000000, '2025-04-30 09:03:12.235749 +00:00', '2023-11-10 05:15:55.253907 +00:00', 'AUDCNY');
INSERT INTO trd."_ExchangeRate" ("Id", "FromCurrencyId", "ToCurrencyId", "BuyingRate", "SellingRate", "AdjustRate", "UpdatedOn", "CreatedOn", "Name") VALUES (2, 840, 156, 7.25220000, 7.28270000, 0.50000000, '2025-04-30 09:03:33.450361 +00:00', '2023-11-10 05:15:55.253907 +00:00', 'USDCNY');
INSERT INTO trd."_ExchangeRate" ("Id", "FromCurrencyId", "ToCurrencyId", "BuyingRate", "SellingRate", "AdjustRate", "UpdatedOn", "CreatedOn", "Name") VALUES (3, 840, 344, 7.73200000, 7.78220000, 1.00000000, '2025-04-30 09:04:00.231457 +00:00', '2023-11-10 05:15:55.253907 +00:00', 'USDHKD');
INSERT INTO trd."_ExchangeRate" ("Id", "FromCurrencyId", "ToCurrencyId", "BuyingRate", "SellingRate", "AdjustRate", "UpdatedOn", "CreatedOn", "Name") VALUES (5, 840, 458, 4.30500000, 4.30500000, 0.75000000, '2025-04-30 09:04:14.762355 +00:00', '2023-11-10 05:15:55.253907 +00:00', 'USDMYR');
INSERT INTO trd."_ExchangeRate" ("Id", "FromCurrencyId", "ToCurrencyId", "BuyingRate", "SellingRate", "AdjustRate", "UpdatedOn", "CreatedOn", "Name") VALUES (7, 840, 764, 33.38000000, 33.38000000, 0.75000000, '2025-04-30 09:04:27.011502 +00:00', '2023-11-10 05:15:55.253907 +00:00', 'USDTHB');
INSERT INTO trd."_ExchangeRate" ("Id", "FromCurrencyId", "ToCurrencyId", "BuyingRate", "SellingRate", "AdjustRate", "UpdatedOn", "CreatedOn", "Name") VALUES (6, 840, 704, 25810.00000000, 26150.00000000, 0.00000000, '2025-04-30 09:04:45.062821 +00:00', '2023-11-10 05:15:55.253907 +00:00', 'USDVND');
INSERT INTO trd."_ExchangeRate" ("Id", "FromCurrencyId", "ToCurrencyId", "BuyingRate", "SellingRate", "AdjustRate", "UpdatedOn", "CreatedOn", "Name") VALUES (8, 840, 360, 16400.00000000, 16810.00000000, 1.00000000, '2025-04-30 09:05:03.563764 +00:00', '2023-11-10 05:15:55.253907 +00:00', 'USDIDR');
INSERT INTO trd."_ExchangeRate" ("Id", "FromCurrencyId", "ToCurrencyId", "BuyingRate", "SellingRate", "AdjustRate", "UpdatedOn", "CreatedOn", "Name") VALUES (9, 840, 608, 55.71800000, 56.30200000, 1.00000000, '2025-04-30 09:05:18.182704 +00:00', '2023-11-10 05:15:55.253907 +00:00', 'USDPHP');
INSERT INTO trd."_ExchangeRate" ("Id", "FromCurrencyId", "ToCurrencyId", "BuyingRate", "SellingRate", "AdjustRate", "UpdatedOn", "CreatedOn", "Name") VALUES (10, 840, 116, 3987.00000000, 4027.00000000, 0.00000000, '2025-04-30 09:05:36.662414 +00:00', '2023-12-01 22:22:44.877818 +00:00', 'USDKHR');
INSERT INTO trd."_ExchangeRate" ("Id", "FromCurrencyId", "ToCurrencyId", "BuyingRate", "SellingRate", "AdjustRate", "UpdatedOn", "CreatedOn", "Name") VALUES (11, 840, 356, 80.56000000, 87.15000000, 1.00000000, '2024-10-04 22:29:41.808473 +00:00', '2023-12-01 22:22:44.877818 +00:00', 'USDINR');
