create table "_PaymentMethod"
(
    "Id"                   bigint generated by default as identity
        constraint "_PaymentMethod_pk"
            primary key,
    "Platform"             integer                                                       not null,
    "MethodType"           varchar(12)              default 'Deposit'::character varying not null,
    "CurrencyId"           integer                  default '-1'::integer                not null,
    "Percentage"           integer                  default 100                          not null,
    "InitialValue"         bigint                                                        not null,
    "MinValue"             bigint                                                        not null,
    "MaxValue"             bigint                                                        not null,
    "Name"                 varchar(32)                                                   not null,
    "Configuration"        jsonb                    default '{}'::jsonb                  not null,
    "CommentCode"          varchar(6)               default ''::character varying        not null,
    "IsHighDollarEnabled"  smallint                                                      not null,
    "IsAutoDepositEnabled" smallint                                                      not null,
    "Group"                varchar(32)              default ''::character varying        not null,
    "Logo"                 varchar(256)             default ''::character varying        not null,
    "Note"                 text                     default ''::text                     not null,
    "Status"               smallint                                                      not null,
    "CreatedOn"            timestamp with time zone default now()                        not null,
    "UpdatedOn"            timestamp with time zone default now()                        not null,
    "ReferenceId"          bigint                   default 0                            not null,
    "OperatorPartyId"      bigint                   default 1                            not null
        constraint "_PaymentMethod__OperatorParty_Id_fk"
            references core."_Party",
    "AvailableCurrencies"  jsonb                    default '{}'::jsonb                  not null,
    "DeletedOn"            timestamp with time zone
);

alter table "_PaymentMethod"
    owner to bcrpro;

create index "IX__PaymentMethod_OperatorPartyId"
    on "_PaymentMethod" ("OperatorPartyId");

create index "IX__PaymentMethod_DeletedOn"
    on "_PaymentMethod" ("DeletedOn");

create index "IX__PaymentMethod_Group"
    on "_PaymentMethod" ("Group");

create index "IX__PaymentMethod_Group_MethodType_Status"
    on "_PaymentMethod" ("Group", "MethodType", "Status");

create index "IX__PaymentMethod_InitialValue"
    on "_PaymentMethod" ("InitialValue");

create index "IX__PaymentMethod_MaxValue"
    on "_PaymentMethod" ("MaxValue");

create index "IX__PaymentMethod_MethodType"
    on "_PaymentMethod" ("MethodType");

create index "IX__PaymentMethod_MinValue"
    on "_PaymentMethod" ("MinValue");

create index "IX__PaymentMethod_Status"
    on "_PaymentMethod" ("Status");

INSERT INTO acct."_PaymentMethod" ("Id", "Platform", "MethodType", "CurrencyId", "Percentage", "InitialValue", "MinValue", "MaxValue", "Name", "Configuration", "CommentCode", "IsHighDollarEnabled", "IsAutoDepositEnabled", "Group", "Logo", "Note", "Status", "CreatedOn", "UpdatedOn", "ReferenceId", "OperatorPartyId", "AvailableCurrencies", "DeletedOn") VALUES (100, 100, 'Deposit', 840, 1, 300, 100, 50000, 'Wire', '{}', '', 0, 0, 'Bank Wire', '', '', 10, '2024-11-13 21:29:28.178327 +00:00', '2024-11-13 21:29:28.178327 +00:00', 0, 1, '{"Currencies": [840], "ApplyAccountCurrency": false}', null);
