create table "_CentralTradeService"
(
    "Id"                     integer generated by default as identity
        constraint "PK__CentralTradeService"
            primary key,
    "Platform"               smallint                               not null,
    "Priority"               integer                                not null,
    "IsAllowAccountCreation" smallint                               not null,
    "CreatedOn"              timestamp with time zone default now() not null,
    "UpdatedOn"              timestamp with time zone default now() not null,
    "Name"                   text                                   not null,
    "Description"            text                                   not null,
    "Configuration"          text                                   not null
);

alter table "_CentralTradeService"
    owner to bcrpro;

INSERT INTO trd."_CentralTradeService" ("Id", "Platform", "Priority", "IsAllowAccountCreation", "CreatedOn", "UpdatedOn", "Name", "Description", "Configuration") VALUES (10, 20, 1, 1, '2023-11-10 05:15:54.263446 +00:00', '2023-11-10 05:15:54.263370 +00:00', 'BCRCO-Real', 'BCRCO-Real', e'{
    "Api": {
        "Host": "192.168.1.1",
        "Port": 7777
    },
    "Groups": [
        "A_Offset"
    ],
    "Database": {
        "Username": "*****",
        "Password": "*****",
        "Host": "*****.amazonaws.com",
        "Port": 7777,
        "Database": "dbdbdbdb",
        "UserTableName": "dbusername",
        "TradeTableName": "dbtablename"
    },
    "AccountPrefixes": {
        "USD": 33000000,
        "AUD": 35000000,
        "EUR": 37000000,
        "GBP": 34000000,
        "DEFAULT": 35000000
    }
}');
INSERT INTO trd."_CentralTradeService" ("Id", "Platform", "Priority", "IsAllowAccountCreation", "CreatedOn", "UpdatedOn", "Name", "Description", "Configuration") VALUES (20, 20, 1, 1, '2023-07-23 18:09:30.680602 +00:00', '2023-07-23 18:09:30.680356 +00:00', 'BCR-Real', 'BCR-Real', e'{
    "Api": {
        "Host": "192.168.1.1",
        "Port": 7777
    },
    "Groups": [
        "test",
    ],
    "Database": {
        "Username": "*****",
        "Password": "*****",
        "Host": "*****.amazonaws.com",
        "Port": 7777,
        "Database": "dbdbdbdb",
        "UserTableName": "dbusername",
        "TradeTableName": "dbtablename"
    },
  "AccountPrefixes": {
    "USD"     :63000000,
    "AUD"     :65000000,
    "DEFAULT" :65000000
  }
}');
INSERT INTO trd."_CentralTradeService" ("Id", "Platform", "Priority", "IsAllowAccountCreation", "CreatedOn", "UpdatedOn", "Name", "Description", "Configuration") VALUES (21, 21, 1, 1, '2023-07-23 18:09:30.680851 +00:00', '2023-07-23 18:09:30.680851 +00:00', 'BCR-Demo', 'BCR-Demo', e'{
    "Api": {
        "Host": "192.168.1.1",
        "Port": 7777
    },
    "Groups": [
        "test",
    ],
    "Database": {
        "Username": "*****",
        "Password": "*****",
        "Host": "*****.amazonaws.com",
        "Port": 7777,
        "Database": "dbdbdbdb",
        "UserTableName": "dbusername",
        "TradeTableName": "dbtablename"
    },
  "AccountPrefixes": {
    "USD"     :63000000,
    "AUD"     :65000000,
    "DEFAULT" :65000000
  }
}');
INSERT INTO trd."_CentralTradeService" ("Id", "Platform", "Priority", "IsAllowAccountCreation", "CreatedOn", "UpdatedOn", "Name", "Description", "Configuration") VALUES (11, 21, 1, 1, '2023-11-10 05:15:54.263546 +00:00', '2023-11-10 05:15:54.263546 +00:00', 'BCRCO-Demo', 'BCRCO-Demo', e'{
    "Api": {
        "Host": "192.168.1.1",
        "Port": 7777
    },
    "Groups": [
        "test",
    ],
    "Database": {
        "Username": "*****",
        "Password": "*****",
        "Host": "*****.amazonaws.com",
        "Port": 7777,
        "Database": "dbdbdbdb",
        "UserTableName": "dbusername",
        "TradeTableName": "dbtablename"
    },
  "AccountPrefixes": {
    "USD"     :63000000,
    "AUD"     :65000000,
    "DEFAULT" :65000000
  }
}');
INSERT INTO trd."_CentralTradeService" ("Id", "Platform", "Priority", "IsAllowAccountCreation", "CreatedOn", "UpdatedOn", "Name", "Description", "Configuration") VALUES (31, 31, 1, 1, '2023-11-10 05:15:54.263547 +00:00', '2023-11-10 05:15:54.263547 +00:00', 'BCR-MT5', 'BCR-MT5 Demo', e'{
    "Api": {
        "Host": "192.168.1.1",
        "Port": 7777
    },
    "Groups": [
        "test",
    ],
    "Database": {
        "Username": "*****",
        "Password": "*****",
        "Host": "*****.amazonaws.com",
        "Port": 7777,
        "Database": "dbdbdbdb",
        "UserTableName": "dbusername",
        "TradeTableName": "dbtablename"
    },
  "AccountPrefixes": {
    "USD"     :63000000,
    "AUD"     :65000000,
    "DEFAULT" :65000000
  }
}');

INSERT INTO trd."_CentralTradeService" ("Id", "Platform", "Priority", "IsAllowAccountCreation", "CreatedOn", "UpdatedOn", "Name", "Description", "Configuration") VALUES (30, 30, 1, 1, '2023-11-10 05:15:54.263546 +00:00', '2023-11-10 05:15:54.263546 +00:00', 'BCR-MT5', 'BCR-MT5 Real', e'{
    "Api": {
        "Host": "https://xxx.xx.xxx",
        "User": "7777",
        "Password": "******"
    },
    "Groups": [
        "xxxx\\\\xxxx\\\\xxxx\\\\xxxx-xxxx",
    ],
    "Database": {
      "Username": "ddddd",
      "Password": "ddddd",
      "Host": "xxxxx.amazonaws.com",
      "Port": 7777,
        "Database": "xxxx",
        "UserTableName": "xxx_xxxs",
        "TradeTableName": "xxx_xxxs"
    },
    "AccountPrefixes": {
        "USD": 32000000,
        "AUD": 36000000,
        "EUR": 37000000,
        "GBP": 34000000,
        "DEFAULT": 36000000
    }
  }');
