create table "_Tag"
(
    "Id"   bigint generated by default as identity
        constraint "_Tag_pk"
            primary key,
    "Type" text not null,
    "Name" text not null
);

alter table "_Tag"
    owner to bcrpro;

create index "_Tag_Name_index"
    on "_Tag" ("Name");

create index "_Tag_Type_index"
    on "_Tag" ("Type");

INSERT INTO core."_Tag" ("Id", "Type", "Name") VALUES (1, 'account', 'Test');
INSERT INTO core."_Tag" ("Id", "Type", "Name") VALUES (2, 'account', 'DailyConfirmEmail');
INSERT INTO core."_Tag" ("Id", "Type", "Name") VALUES (3, 'account', 'NewRebateTest');
INSERT INTO core."_Tag" ("Id", "Type", "Name") VALUES (4, 'account', 'AddPips');
INSERT INTO core."_Tag" ("Id", "Type", "Name") VALUES (5, 'account', 'AddCommission');
INSERT INTO core."_Tag" ("Id", "Type", "Name") VALUES (6, 'account', 'DefaultAgentAccount');
INSERT INTO core."_Tag" ("Id", "Type", "Name") VALUES (7, 'account', 'DefaultSalesAccount');
INSERT INTO core."_Tag" ("Id", "Type", "Name") VALUES (8, 'account', 'AutoCreate');
INSERT INTO core."_Tag" ("Id", "Type", "Name") VALUES (9, 'account', 'AutoCreateConfirmed');
INSERT INTO core."_Tag" ("Id", "Type", "Name") VALUES (10, 'party', 'HasClosedAccount');
INSERT INTO core."_Tag" ("Id", "Type", "Name") VALUES (11, 'party', 'DelayedReview');
INSERT INTO core."_Tag" ("Id", "Type", "Name") VALUES (12, 'party', 'EventShopActivity');
INSERT INTO core."_Tag" ("Id", "Type", "Name") VALUES (13, 'party', 'Special');
INSERT INTO core."_Tag" ("Id", "Type", "Name") VALUES (14, 'party', 'SalesWithdrawalNotice');
INSERT INTO core."_Tag" ("Id", "Type", "Name") VALUES (15, 'party', 'NoPromotionEmail');
INSERT INTO core."_Tag" ("Id", "Type", "Name") VALUES (16, 'account', 'PauseReleaseRebate');
