use anyhow::Result;
use sqlx::PgPool;

// ── Parent table DDL ──────────────────────────────────────────────────────────

/// Create all K8s partitioned parent tables if they don't already exist.
/// Safe to call repeatedly — all DDL uses IF NOT EXISTS.
pub async fn ensure_parent_tables(pool: &PgPool) -> Result<()> {
    // core.matter_k8s — non-partitioned; enables FK from activity_k8s.MatterId.
    // Migrates from old partitioned core."_MatterK8s" if present.
    sqlx::query(
        r#"DO $$ BEGIN
               IF EXISTS (
                   SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
                   WHERE n.nspname = 'core' AND c.relname = '_MatterK8s' AND c.relkind = 'p'
               ) THEN
                   DROP TABLE IF EXISTS core."_MatterK8s_2025";
                   DROP TABLE IF EXISTS core."_MatterK8s_2026";
                   DROP TABLE IF EXISTS core."_MatterK8s_2027";
                   DROP TABLE IF EXISTS core."_MatterK8s_2028";
                   DROP TABLE core."_MatterK8s";
               END IF;
           END $$"#,
    )
    .execute(pool)
    .await?;

    sqlx::query(
        r#"CREATE TABLE IF NOT EXISTS core.matter_k8s (
            "Id"       BIGINT       NOT NULL,
            "Pid"      BIGINT,
            "Type"     INT          NOT NULL,
            "StateId"  INT          NOT NULL,
            "PostedOn" TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
            "StatedOn" TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
            PRIMARY KEY ("Id")
        )"#,
    )
    .execute(pool)
    .await?;

    sqlx::query(
        r#"CREATE INDEX IF NOT EXISTS ix_matter_k8s_state_id
           ON core.matter_k8s ("StateId")"#,
    )
    .execute(pool)
    .await?;

    sqlx::query(
        r#"CREATE INDEX IF NOT EXISTS ix_matter_k8s_type
           ON core.matter_k8s ("Type")"#,
    )
    .execute(pool)
    .await?;

    // core.activity_k8s — partitioned by PerformedOn
    sqlx::query(
        r#"CREATE TABLE IF NOT EXISTS core.activity_k8s (
            "Id"          BIGINT       GENERATED BY DEFAULT AS IDENTITY,
            "MatterId"    BIGINT       NOT NULL,
            "PartyId"     BIGINT       NOT NULL,
            "PerformedOn" TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
            "OnStateId"   INT          NOT NULL,
            "ActionId"    INT          NOT NULL DEFAULT 0,
            "ToStateId"   INT          NOT NULL,
            "Data"        TEXT         NOT NULL DEFAULT '',
            PRIMARY KEY ("Id", "PerformedOn")
        ) PARTITION BY RANGE ("PerformedOn")"#,
    )
    .execute(pool)
    .await?;

    sqlx::query(
        r#"CREATE INDEX IF NOT EXISTS ix_activity_k8s_matter_id
           ON core.activity_k8s ("MatterId")"#,
    )
    .execute(pool)
    .await?;

    sqlx::query(
        r#"CREATE INDEX IF NOT EXISTS ix_activity_k8s_party_id
           ON core.activity_k8s ("PartyId")"#,
    )
    .execute(pool)
    .await?;

    // FK: PartyId → core."_Party"("Id")
    sqlx::query(
        r#"DO $$ BEGIN
               ALTER TABLE core.activity_k8s
               ADD CONSTRAINT fk_activity_k8s_party_id
               FOREIGN KEY ("PartyId") REFERENCES core."_Party"("Id");
           EXCEPTION WHEN duplicate_object THEN NULL;
           END $$"#,
    )
    .execute(pool)
    .await?;

    // FK: MatterId → core.matter_k8s("Id")
    sqlx::query(
        r#"DO $$ BEGIN
               ALTER TABLE core.activity_k8s
               ADD CONSTRAINT fk_activity_k8s_matter_id
               FOREIGN KEY ("MatterId") REFERENCES core.matter_k8s("Id");
           EXCEPTION WHEN duplicate_object THEN NULL;
           END $$"#,
    )
    .execute(pool)
    .await?;

    // acct.wallet_transaction_k8s — partitioned by CreatedOn
    sqlx::query(
        r#"CREATE TABLE IF NOT EXISTS acct.wallet_transaction_k8s (
            "Id"          BIGINT       GENERATED BY DEFAULT AS IDENTITY,
            "WalletId"    BIGINT       NOT NULL,
            "InvoiceId"   BIGINT,
            "MatterId"    BIGINT       NOT NULL,
            "PrevBalance" BIGINT       NOT NULL DEFAULT 0,
            "Amount"      BIGINT       NOT NULL DEFAULT 0,
            "CreatedOn"   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
            "UpdatedOn"   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
            PRIMARY KEY ("Id", "CreatedOn")
        ) PARTITION BY RANGE ("CreatedOn")"#,
    )
    .execute(pool)
    .await?;

    sqlx::query(
        r#"CREATE INDEX IF NOT EXISTS ix_wallet_transaction_k8s_matter_id
           ON acct.wallet_transaction_k8s ("MatterId")"#,
    )
    .execute(pool)
    .await?;

    sqlx::query(
        r#"CREATE INDEX IF NOT EXISTS ix_wallet_transaction_k8s_wallet_id
           ON acct.wallet_transaction_k8s ("WalletId")"#,
    )
    .execute(pool)
    .await?;

    // FK: WalletId → acct."_Wallet"("Id")
    sqlx::query(
        r#"DO $$ BEGIN
               ALTER TABLE acct.wallet_transaction_k8s
               ADD CONSTRAINT fk_wallet_transaction_k8s_wallet_id
               FOREIGN KEY ("WalletId") REFERENCES acct."_Wallet"("Id");
           EXCEPTION WHEN duplicate_object THEN NULL;
           END $$"#,
    )
    .execute(pool)
    .await?;

    // FK: InvoiceId → acct."_Invoice"("Id") (nullable)
    sqlx::query(
        r#"DO $$ BEGIN
               ALTER TABLE acct.wallet_transaction_k8s
               ADD CONSTRAINT fk_wallet_transaction_k8s_invoice_id
               FOREIGN KEY ("InvoiceId") REFERENCES acct."_Invoice"("Id");
           EXCEPTION WHEN duplicate_object THEN NULL;
           END $$"#,
    )
    .execute(pool)
    .await?;

    // trd.trade_rebate_k8s — partitioned by ClosedOn
    sqlx::query(
        r#"CREATE TABLE IF NOT EXISTS trd.trade_rebate_k8s (
            "Id"             BIGINT         NOT NULL,
            "AccountId"      BIGINT,
            "TradeServiceId" INT            NOT NULL,
            "Ticket"         BIGINT         NOT NULL,
            "AccountNumber"  BIGINT         NOT NULL,
            "CurrencyId"     INT            NOT NULL DEFAULT -1,
            "Volume"         INT            NOT NULL DEFAULT 0,
            "Status"         INT            NOT NULL DEFAULT 0,
            "RuleType"       INT            NOT NULL DEFAULT 199,
            "CreatedOn"      TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
            "UpdatedOn"      TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
            "ClosedOn"       TIMESTAMPTZ    NOT NULL,
            "OpenedOn"       TIMESTAMPTZ    NOT NULL,
            "TimeStamp"      BIGINT         NOT NULL DEFAULT 0,
            "Action"         INT            NOT NULL DEFAULT 0,
            "DealId"         BIGINT         NOT NULL DEFAULT 0,
            "Symbol"         VARCHAR(32)    NOT NULL DEFAULT '',
            "ReferPath"      VARCHAR(512)   NOT NULL DEFAULT '',
            "Commission"     NUMERIC(18,8)  NOT NULL DEFAULT 0,
            "Swaps"          NUMERIC(18,8)  NOT NULL DEFAULT 0,
            "OpenPrice"      NUMERIC(18,8)  NOT NULL DEFAULT 0,
            "ClosePrice"     NUMERIC(18,8)  NOT NULL DEFAULT 0,
            "Profit"         NUMERIC(18,8)  NOT NULL DEFAULT 0,
            "Reason"         INT            NOT NULL DEFAULT 0,
            PRIMARY KEY ("Id", "ClosedOn")
        ) PARTITION BY RANGE ("ClosedOn")"#,
    )
    .execute(pool)
    .await?;

    // Snowflake IDs are globally unique by construction; a regular index suffices.
    sqlx::query(
        r#"CREATE INDEX IF NOT EXISTS ix_trade_rebate_k8s_id
           ON trd.trade_rebate_k8s ("Id")"#,
    )
    .execute(pool)
    .await?;

    // Per-partition dedup: partition key (ClosedOn) must be included in unique index.
    sqlx::query(
        r#"CREATE UNIQUE INDEX IF NOT EXISTS ux_trade_rebate_k8s_ticket_service_closed
           ON trd.trade_rebate_k8s ("Ticket", "TradeServiceId", "ClosedOn")"#,
    )
    .execute(pool)
    .await?;

    sqlx::query(
        r#"CREATE INDEX IF NOT EXISTS ix_trade_rebate_k8s_account_number
           ON trd.trade_rebate_k8s ("AccountNumber")"#,
    )
    .execute(pool)
    .await?;

    // FK: AccountId → trd."_Account"("Id")
    sqlx::query(
        r#"DO $$ BEGIN
               ALTER TABLE trd.trade_rebate_k8s
               ADD CONSTRAINT fk_trade_rebate_k8s_account_id
               FOREIGN KEY ("AccountId") REFERENCES trd."_Account"("Id");
           EXCEPTION WHEN duplicate_object THEN NULL;
           END $$"#,
    )
    .execute(pool)
    .await?;

    // FK: TradeServiceId → trd."_TradeService"("Id")
    sqlx::query(
        r#"DO $$ BEGIN
               ALTER TABLE trd.trade_rebate_k8s
               ADD CONSTRAINT fk_trade_rebate_k8s_trade_service_id
               FOREIGN KEY ("TradeServiceId") REFERENCES trd."_TradeService"("Id");
           EXCEPTION WHEN duplicate_object THEN NULL;
           END $$"#,
    )
    .execute(pool)
    .await?;

    // trd.rebate_k8s — partitioned by CreatedOn
    sqlx::query(
        r#"CREATE TABLE IF NOT EXISTS trd.rebate_k8s (
            "Id"            BIGINT        NOT NULL,
            "PartyId"       BIGINT        NOT NULL,
            "AccountId"     BIGINT        NOT NULL,
            "FundType"      INT           NOT NULL DEFAULT 0,
            "CurrencyId"    INT           NOT NULL DEFAULT -1,
            "Amount"        NUMERIC(20,8) NOT NULL DEFAULT 0,
            "TradeRebateId" BIGINT,
            "HoldUntilOn"   TIMESTAMPTZ,
            "Information"   TEXT          NOT NULL DEFAULT '',
            "CreatedOn"     TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
            PRIMARY KEY ("Id", "CreatedOn")
        ) PARTITION BY RANGE ("CreatedOn")"#,
    )
    .execute(pool)
    .await?;

    sqlx::query(
        r#"CREATE INDEX IF NOT EXISTS ix_rebate_k8s_account_id
           ON trd.rebate_k8s ("AccountId")"#,
    )
    .execute(pool)
    .await?;

    sqlx::query(
        r#"CREATE INDEX IF NOT EXISTS ix_rebate_k8s_party_id
           ON trd.rebate_k8s ("PartyId")"#,
    )
    .execute(pool)
    .await?;

    sqlx::query(
        r#"CREATE INDEX IF NOT EXISTS ix_rebate_k8s_trade_rebate_id
           ON trd.rebate_k8s ("TradeRebateId")"#,
    )
    .execute(pool)
    .await?;

    // FK: AccountId → trd."_Account"("Id")
    sqlx::query(
        r#"DO $$ BEGIN
               ALTER TABLE trd.rebate_k8s
               ADD CONSTRAINT fk_rebate_k8s_account_id
               FOREIGN KEY ("AccountId") REFERENCES trd."_Account"("Id");
           EXCEPTION WHEN duplicate_object THEN NULL;
           END $$"#,
    )
    .execute(pool)
    .await?;

    Ok(())
}

// ── Year sub-partition management ─────────────────────────────────────────────

/// Ensure the year sub-partition exists for a snake_case K8s parent table.
/// E.g. ensure_year_partition_snake(pool, "trd", "trade_rebate_k8s", 2026) creates
/// trd.trade_rebate_k8s_2026 FOR VALUES FROM ('2026-01-01') TO ('2027-01-01').
pub async fn ensure_year_partition_snake(
    pool: &PgPool,
    schema: &str,
    parent: &str,
    year: i32,
) -> Result<()> {
    let partition = format!("{schema}.{parent}_{year}");
    let parent_full = format!("{schema}.{parent}");
    let from = format!("{}-01-01", year);
    let to = format!("{}-01-01", year + 1);

    sqlx::query(&format!(
        r#"CREATE TABLE IF NOT EXISTS {partition}
           PARTITION OF {parent_full}
           FOR VALUES FROM ('{from}') TO ('{to}')"#
    ))
    .execute(pool)
    .await?;

    Ok(())
}
