use anyhow::Result;
use sqlx::PgPool;

// ── Parent table DDL ──────────────────────────────────────────────────────────

/// Create all K8s partitioned parent tables if they don't already exist.
/// Safe to call repeatedly — all DDL uses IF NOT EXISTS.
pub async fn ensure_parent_tables(pool: &PgPool) -> Result<()> {
    // core.matter_k8s — non-partitioned; enables FK from activity_k8s.matter_id.
    // Migrates from old partitioned core."_MatterK8s" if present.
    sqlx::query(
        r#"DO $$ BEGIN
               IF EXISTS (
                   SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
                   WHERE n.nspname = 'core' AND c.relname = '_MatterK8s' AND c.relkind = 'p'
               ) THEN
                   DROP TABLE IF EXISTS core."_MatterK8s_2025";
                   DROP TABLE IF EXISTS core."_MatterK8s_2026";
                   DROP TABLE IF EXISTS core."_MatterK8s_2027";
                   DROP TABLE IF EXISTS core."_MatterK8s_2028";
                   DROP TABLE core."_MatterK8s";
               END IF;
           END $$"#,
    )
    .execute(pool)
    .await?;

    sqlx::query(
        r#"CREATE TABLE IF NOT EXISTS core.matter_k8s (
            id        BIGINT       NOT NULL,
            pid       BIGINT,
            type      INT          NOT NULL,
            state_id  INT          NOT NULL,
            posted_on TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
            stated_on TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
            PRIMARY KEY (id)
        )"#,
    )
    .execute(pool)
    .await?;

    // Migrate existing PascalCase columns to snake_case (idempotent)
    sqlx::query(
        r#"DO $$ BEGIN
               IF EXISTS (SELECT 1 FROM information_schema.columns
                          WHERE table_schema='core' AND table_name='matter_k8s' AND column_name='Id') THEN
                   ALTER TABLE core.matter_k8s RENAME COLUMN "Id" TO id;
               END IF;
               IF EXISTS (SELECT 1 FROM information_schema.columns
                          WHERE table_schema='core' AND table_name='matter_k8s' AND column_name='Pid') THEN
                   ALTER TABLE core.matter_k8s RENAME COLUMN "Pid" TO pid;
               END IF;
               IF EXISTS (SELECT 1 FROM information_schema.columns
                          WHERE table_schema='core' AND table_name='matter_k8s' AND column_name='Type') THEN
                   ALTER TABLE core.matter_k8s RENAME COLUMN "Type" TO type;
               END IF;
               IF EXISTS (SELECT 1 FROM information_schema.columns
                          WHERE table_schema='core' AND table_name='matter_k8s' AND column_name='StateId') THEN
                   ALTER TABLE core.matter_k8s RENAME COLUMN "StateId" TO state_id;
               END IF;
               IF EXISTS (SELECT 1 FROM information_schema.columns
                          WHERE table_schema='core' AND table_name='matter_k8s' AND column_name='PostedOn') THEN
                   ALTER TABLE core.matter_k8s RENAME COLUMN "PostedOn" TO posted_on;
               END IF;
               IF EXISTS (SELECT 1 FROM information_schema.columns
                          WHERE table_schema='core' AND table_name='matter_k8s' AND column_name='StatedOn') THEN
                   ALTER TABLE core.matter_k8s RENAME COLUMN "StatedOn" TO stated_on;
               END IF;
           END $$"#,
    )
    .execute(pool)
    .await?;

    sqlx::query(
        r#"CREATE INDEX IF NOT EXISTS ix_matter_k8s_state_id
           ON core.matter_k8s (state_id)"#,
    )
    .execute(pool)
    .await?;

    sqlx::query(
        r#"CREATE INDEX IF NOT EXISTS ix_matter_k8s_type
           ON core.matter_k8s (type)"#,
    )
    .execute(pool)
    .await?;

    // core.activity_k8s — partitioned by performed_on
    sqlx::query(
        r#"CREATE TABLE IF NOT EXISTS core.activity_k8s (
            id           BIGINT       GENERATED BY DEFAULT AS IDENTITY,
            matter_id    BIGINT       NOT NULL,
            party_id     BIGINT       NOT NULL,
            performed_on TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
            on_state_id  INT          NOT NULL,
            action_id    INT          NOT NULL DEFAULT 0,
            to_state_id  INT          NOT NULL,
            data         TEXT         NOT NULL DEFAULT '',
            PRIMARY KEY (id, performed_on)
        ) PARTITION BY RANGE (performed_on)"#,
    )
    .execute(pool)
    .await?;

    // Migrate existing PascalCase columns to snake_case (idempotent)
    sqlx::query(
        r#"DO $$ BEGIN
               IF EXISTS (SELECT 1 FROM information_schema.columns
                          WHERE table_schema='core' AND table_name='activity_k8s' AND column_name='Id') THEN
                   ALTER TABLE core.activity_k8s RENAME COLUMN "Id" TO id;
               END IF;
               IF EXISTS (SELECT 1 FROM information_schema.columns
                          WHERE table_schema='core' AND table_name='activity_k8s' AND column_name='MatterId') THEN
                   ALTER TABLE core.activity_k8s RENAME COLUMN "MatterId" TO matter_id;
               END IF;
               IF EXISTS (SELECT 1 FROM information_schema.columns
                          WHERE table_schema='core' AND table_name='activity_k8s' AND column_name='PartyId') THEN
                   ALTER TABLE core.activity_k8s RENAME COLUMN "PartyId" TO party_id;
               END IF;
               IF EXISTS (SELECT 1 FROM information_schema.columns
                          WHERE table_schema='core' AND table_name='activity_k8s' AND column_name='PerformedOn') THEN
                   ALTER TABLE core.activity_k8s RENAME COLUMN "PerformedOn" TO performed_on;
               END IF;
               IF EXISTS (SELECT 1 FROM information_schema.columns
                          WHERE table_schema='core' AND table_name='activity_k8s' AND column_name='OnStateId') THEN
                   ALTER TABLE core.activity_k8s RENAME COLUMN "OnStateId" TO on_state_id;
               END IF;
               IF EXISTS (SELECT 1 FROM information_schema.columns
                          WHERE table_schema='core' AND table_name='activity_k8s' AND column_name='ActionId') THEN
                   ALTER TABLE core.activity_k8s RENAME COLUMN "ActionId" TO action_id;
               END IF;
               IF EXISTS (SELECT 1 FROM information_schema.columns
                          WHERE table_schema='core' AND table_name='activity_k8s' AND column_name='ToStateId') THEN
                   ALTER TABLE core.activity_k8s RENAME COLUMN "ToStateId" TO to_state_id;
               END IF;
               IF EXISTS (SELECT 1 FROM information_schema.columns
                          WHERE table_schema='core' AND table_name='activity_k8s' AND column_name='Data') THEN
                   ALTER TABLE core.activity_k8s RENAME COLUMN "Data" TO data;
               END IF;
           END $$"#,
    )
    .execute(pool)
    .await?;

    sqlx::query(
        r#"CREATE INDEX IF NOT EXISTS ix_activity_k8s_matter_id
           ON core.activity_k8s (matter_id)"#,
    )
    .execute(pool)
    .await?;

    sqlx::query(
        r#"CREATE INDEX IF NOT EXISTS ix_activity_k8s_party_id
           ON core.activity_k8s (party_id)"#,
    )
    .execute(pool)
    .await?;

    // FK: party_id → core."_Party"("Id")
    sqlx::query(
        r#"DO $$ BEGIN
               ALTER TABLE core.activity_k8s
               ADD CONSTRAINT fk_activity_k8s_party_id
               FOREIGN KEY (party_id) REFERENCES core."_Party"("Id");
           EXCEPTION WHEN duplicate_object THEN NULL;
           END $$"#,
    )
    .execute(pool)
    .await?;

    // FK: matter_id → core.matter_k8s(id)
    sqlx::query(
        r#"DO $$ BEGIN
               ALTER TABLE core.activity_k8s
               ADD CONSTRAINT fk_activity_k8s_matter_id
               FOREIGN KEY (matter_id) REFERENCES core.matter_k8s(id);
           EXCEPTION WHEN duplicate_object THEN NULL;
           END $$"#,
    )
    .execute(pool)
    .await?;

    // acct.wallet_transaction_k8s — partitioned by created_on
    sqlx::query(
        r#"CREATE TABLE IF NOT EXISTS acct.wallet_transaction_k8s (
            id           BIGINT       GENERATED BY DEFAULT AS IDENTITY,
            wallet_id    BIGINT       NOT NULL,
            invoice_id   BIGINT,
            matter_id    BIGINT       NOT NULL,
            prev_balance BIGINT       NOT NULL DEFAULT 0,
            amount       BIGINT       NOT NULL DEFAULT 0,
            created_on   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
            updated_on   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
            PRIMARY KEY (id, created_on)
        ) PARTITION BY RANGE (created_on)"#,
    )
    .execute(pool)
    .await?;

    // Migrate existing PascalCase columns to snake_case (idempotent)
    sqlx::query(
        r#"DO $$ BEGIN
               IF EXISTS (SELECT 1 FROM information_schema.columns
                          WHERE table_schema='acct' AND table_name='wallet_transaction_k8s' AND column_name='Id') THEN
                   ALTER TABLE acct.wallet_transaction_k8s RENAME COLUMN "Id" TO id;
               END IF;
               IF EXISTS (SELECT 1 FROM information_schema.columns
                          WHERE table_schema='acct' AND table_name='wallet_transaction_k8s' AND column_name='WalletId') THEN
                   ALTER TABLE acct.wallet_transaction_k8s RENAME COLUMN "WalletId" TO wallet_id;
               END IF;
               IF EXISTS (SELECT 1 FROM information_schema.columns
                          WHERE table_schema='acct' AND table_name='wallet_transaction_k8s' AND column_name='InvoiceId') THEN
                   ALTER TABLE acct.wallet_transaction_k8s RENAME COLUMN "InvoiceId" TO invoice_id;
               END IF;
               IF EXISTS (SELECT 1 FROM information_schema.columns
                          WHERE table_schema='acct' AND table_name='wallet_transaction_k8s' AND column_name='MatterId') THEN
                   ALTER TABLE acct.wallet_transaction_k8s RENAME COLUMN "MatterId" TO matter_id;
               END IF;
               IF EXISTS (SELECT 1 FROM information_schema.columns
                          WHERE table_schema='acct' AND table_name='wallet_transaction_k8s' AND column_name='PrevBalance') THEN
                   ALTER TABLE acct.wallet_transaction_k8s RENAME COLUMN "PrevBalance" TO prev_balance;
               END IF;
               IF EXISTS (SELECT 1 FROM information_schema.columns
                          WHERE table_schema='acct' AND table_name='wallet_transaction_k8s' AND column_name='Amount') THEN
                   ALTER TABLE acct.wallet_transaction_k8s RENAME COLUMN "Amount" TO amount;
               END IF;
               IF EXISTS (SELECT 1 FROM information_schema.columns
                          WHERE table_schema='acct' AND table_name='wallet_transaction_k8s' AND column_name='CreatedOn') THEN
                   ALTER TABLE acct.wallet_transaction_k8s RENAME COLUMN "CreatedOn" TO created_on;
               END IF;
               IF EXISTS (SELECT 1 FROM information_schema.columns
                          WHERE table_schema='acct' AND table_name='wallet_transaction_k8s' AND column_name='UpdatedOn') THEN
                   ALTER TABLE acct.wallet_transaction_k8s RENAME COLUMN "UpdatedOn" TO updated_on;
               END IF;
           END $$"#,
    )
    .execute(pool)
    .await?;

    sqlx::query(
        r#"CREATE INDEX IF NOT EXISTS ix_wallet_transaction_k8s_matter_id
           ON acct.wallet_transaction_k8s (matter_id)"#,
    )
    .execute(pool)
    .await?;

    sqlx::query(
        r#"CREATE INDEX IF NOT EXISTS ix_wallet_transaction_k8s_wallet_id
           ON acct.wallet_transaction_k8s (wallet_id)"#,
    )
    .execute(pool)
    .await?;

    // FK: wallet_id → acct."_Wallet"("Id")
    sqlx::query(
        r#"DO $$ BEGIN
               ALTER TABLE acct.wallet_transaction_k8s
               ADD CONSTRAINT fk_wallet_transaction_k8s_wallet_id
               FOREIGN KEY (wallet_id) REFERENCES acct."_Wallet"("Id");
           EXCEPTION WHEN duplicate_object THEN NULL;
           END $$"#,
    )
    .execute(pool)
    .await?;

    // FK: invoice_id → acct."_Invoice"("Id") (nullable)
    sqlx::query(
        r#"DO $$ BEGIN
               ALTER TABLE acct.wallet_transaction_k8s
               ADD CONSTRAINT fk_wallet_transaction_k8s_invoice_id
               FOREIGN KEY (invoice_id) REFERENCES acct."_Invoice"("Id");
           EXCEPTION WHEN duplicate_object THEN NULL;
           END $$"#,
    )
    .execute(pool)
    .await?;

    // FK: matter_id → core.matter_k8s(id)
    sqlx::query(
        r#"DO $$ BEGIN
               ALTER TABLE acct.wallet_transaction_k8s
               ADD CONSTRAINT fk_wallet_transaction_k8s_matter_id
               FOREIGN KEY (matter_id) REFERENCES core.matter_k8s(id);
           EXCEPTION WHEN duplicate_object THEN NULL;
           END $$"#,
    )
    .execute(pool)
    .await?;

    // trd.trade_rebate_k8s — partitioned by closed_on
    sqlx::query(
        r#"CREATE TABLE IF NOT EXISTS trd.trade_rebate_k8s (
            id               BIGINT         NOT NULL,
            account_id       BIGINT,
            trade_service_id INT            NOT NULL,
            ticket           BIGINT         NOT NULL,
            account_number   BIGINT         NOT NULL,
            currency_id      INT            NOT NULL DEFAULT -1,
            volume           INT            NOT NULL DEFAULT 0,
            status           INT            NOT NULL DEFAULT 0,
            rule_type        INT            NOT NULL DEFAULT 199,
            created_on       TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
            updated_on       TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
            closed_on        TIMESTAMPTZ    NOT NULL,
            opened_on        TIMESTAMPTZ    NOT NULL,
            time_stamp       BIGINT         NOT NULL DEFAULT 0,
            action           INT            NOT NULL DEFAULT 0,
            deal_id          BIGINT         NOT NULL DEFAULT 0,
            symbol           VARCHAR(32)    NOT NULL DEFAULT '',
            refer_path       VARCHAR(512)   NOT NULL DEFAULT '',
            commission       NUMERIC(18,8)  NOT NULL DEFAULT 0,
            swaps            NUMERIC(18,8)  NOT NULL DEFAULT 0,
            open_price       NUMERIC(18,8)  NOT NULL DEFAULT 0,
            close_price      NUMERIC(18,8)  NOT NULL DEFAULT 0,
            profit           NUMERIC(18,8)  NOT NULL DEFAULT 0,
            reason           INT            NOT NULL DEFAULT 0,
            PRIMARY KEY (id, closed_on)
        ) PARTITION BY RANGE (closed_on)"#,
    )
    .execute(pool)
    .await?;

    // Migrate existing PascalCase columns to snake_case (idempotent)
    sqlx::query(
        r#"DO $$ BEGIN
               IF EXISTS (SELECT 1 FROM information_schema.columns
                          WHERE table_schema='trd' AND table_name='trade_rebate_k8s' AND column_name='Id') THEN
                   ALTER TABLE trd.trade_rebate_k8s RENAME COLUMN "Id" TO id;
               END IF;
               IF EXISTS (SELECT 1 FROM information_schema.columns
                          WHERE table_schema='trd' AND table_name='trade_rebate_k8s' AND column_name='AccountId') THEN
                   ALTER TABLE trd.trade_rebate_k8s RENAME COLUMN "AccountId" TO account_id;
               END IF;
               IF EXISTS (SELECT 1 FROM information_schema.columns
                          WHERE table_schema='trd' AND table_name='trade_rebate_k8s' AND column_name='TradeServiceId') THEN
                   ALTER TABLE trd.trade_rebate_k8s RENAME COLUMN "TradeServiceId" TO trade_service_id;
               END IF;
               IF EXISTS (SELECT 1 FROM information_schema.columns
                          WHERE table_schema='trd' AND table_name='trade_rebate_k8s' AND column_name='Ticket') THEN
                   ALTER TABLE trd.trade_rebate_k8s RENAME COLUMN "Ticket" TO ticket;
               END IF;
               IF EXISTS (SELECT 1 FROM information_schema.columns
                          WHERE table_schema='trd' AND table_name='trade_rebate_k8s' AND column_name='AccountNumber') THEN
                   ALTER TABLE trd.trade_rebate_k8s RENAME COLUMN "AccountNumber" TO account_number;
               END IF;
               IF EXISTS (SELECT 1 FROM information_schema.columns
                          WHERE table_schema='trd' AND table_name='trade_rebate_k8s' AND column_name='CurrencyId') THEN
                   ALTER TABLE trd.trade_rebate_k8s RENAME COLUMN "CurrencyId" TO currency_id;
               END IF;
               IF EXISTS (SELECT 1 FROM information_schema.columns
                          WHERE table_schema='trd' AND table_name='trade_rebate_k8s' AND column_name='Volume') THEN
                   ALTER TABLE trd.trade_rebate_k8s RENAME COLUMN "Volume" TO volume;
               END IF;
               IF EXISTS (SELECT 1 FROM information_schema.columns
                          WHERE table_schema='trd' AND table_name='trade_rebate_k8s' AND column_name='Status') THEN
                   ALTER TABLE trd.trade_rebate_k8s RENAME COLUMN "Status" TO status;
               END IF;
               IF EXISTS (SELECT 1 FROM information_schema.columns
                          WHERE table_schema='trd' AND table_name='trade_rebate_k8s' AND column_name='RuleType') THEN
                   ALTER TABLE trd.trade_rebate_k8s RENAME COLUMN "RuleType" TO rule_type;
               END IF;
               IF EXISTS (SELECT 1 FROM information_schema.columns
                          WHERE table_schema='trd' AND table_name='trade_rebate_k8s' AND column_name='CreatedOn') THEN
                   ALTER TABLE trd.trade_rebate_k8s RENAME COLUMN "CreatedOn" TO created_on;
               END IF;
               IF EXISTS (SELECT 1 FROM information_schema.columns
                          WHERE table_schema='trd' AND table_name='trade_rebate_k8s' AND column_name='UpdatedOn') THEN
                   ALTER TABLE trd.trade_rebate_k8s RENAME COLUMN "UpdatedOn" TO updated_on;
               END IF;
               IF EXISTS (SELECT 1 FROM information_schema.columns
                          WHERE table_schema='trd' AND table_name='trade_rebate_k8s' AND column_name='ClosedOn') THEN
                   ALTER TABLE trd.trade_rebate_k8s RENAME COLUMN "ClosedOn" TO closed_on;
               END IF;
               IF EXISTS (SELECT 1 FROM information_schema.columns
                          WHERE table_schema='trd' AND table_name='trade_rebate_k8s' AND column_name='OpenedOn') THEN
                   ALTER TABLE trd.trade_rebate_k8s RENAME COLUMN "OpenedOn" TO opened_on;
               END IF;
               IF EXISTS (SELECT 1 FROM information_schema.columns
                          WHERE table_schema='trd' AND table_name='trade_rebate_k8s' AND column_name='TimeStamp') THEN
                   ALTER TABLE trd.trade_rebate_k8s RENAME COLUMN "TimeStamp" TO time_stamp;
               END IF;
               IF EXISTS (SELECT 1 FROM information_schema.columns
                          WHERE table_schema='trd' AND table_name='trade_rebate_k8s' AND column_name='Action') THEN
                   ALTER TABLE trd.trade_rebate_k8s RENAME COLUMN "Action" TO action;
               END IF;
               IF EXISTS (SELECT 1 FROM information_schema.columns
                          WHERE table_schema='trd' AND table_name='trade_rebate_k8s' AND column_name='DealId') THEN
                   ALTER TABLE trd.trade_rebate_k8s RENAME COLUMN "DealId" TO deal_id;
               END IF;
               IF EXISTS (SELECT 1 FROM information_schema.columns
                          WHERE table_schema='trd' AND table_name='trade_rebate_k8s' AND column_name='Symbol') THEN
                   ALTER TABLE trd.trade_rebate_k8s RENAME COLUMN "Symbol" TO symbol;
               END IF;
               IF EXISTS (SELECT 1 FROM information_schema.columns
                          WHERE table_schema='trd' AND table_name='trade_rebate_k8s' AND column_name='ReferPath') THEN
                   ALTER TABLE trd.trade_rebate_k8s RENAME COLUMN "ReferPath" TO refer_path;
               END IF;
               IF EXISTS (SELECT 1 FROM information_schema.columns
                          WHERE table_schema='trd' AND table_name='trade_rebate_k8s' AND column_name='Commission') THEN
                   ALTER TABLE trd.trade_rebate_k8s RENAME COLUMN "Commission" TO commission;
               END IF;
               IF EXISTS (SELECT 1 FROM information_schema.columns
                          WHERE table_schema='trd' AND table_name='trade_rebate_k8s' AND column_name='Swaps') THEN
                   ALTER TABLE trd.trade_rebate_k8s RENAME COLUMN "Swaps" TO swaps;
               END IF;
               IF EXISTS (SELECT 1 FROM information_schema.columns
                          WHERE table_schema='trd' AND table_name='trade_rebate_k8s' AND column_name='OpenPrice') THEN
                   ALTER TABLE trd.trade_rebate_k8s RENAME COLUMN "OpenPrice" TO open_price;
               END IF;
               IF EXISTS (SELECT 1 FROM information_schema.columns
                          WHERE table_schema='trd' AND table_name='trade_rebate_k8s' AND column_name='ClosePrice') THEN
                   ALTER TABLE trd.trade_rebate_k8s RENAME COLUMN "ClosePrice" TO close_price;
               END IF;
               IF EXISTS (SELECT 1 FROM information_schema.columns
                          WHERE table_schema='trd' AND table_name='trade_rebate_k8s' AND column_name='Profit') THEN
                   ALTER TABLE trd.trade_rebate_k8s RENAME COLUMN "Profit" TO profit;
               END IF;
               IF EXISTS (SELECT 1 FROM information_schema.columns
                          WHERE table_schema='trd' AND table_name='trade_rebate_k8s' AND column_name='Reason') THEN
                   ALTER TABLE trd.trade_rebate_k8s RENAME COLUMN "Reason" TO reason;
               END IF;
           END $$"#,
    )
    .execute(pool)
    .await?;

    // Snowflake IDs are globally unique by construction; a regular index suffices.
    sqlx::query(
        r#"CREATE INDEX IF NOT EXISTS ix_trade_rebate_k8s_id
           ON trd.trade_rebate_k8s (id)"#,
    )
    .execute(pool)
    .await?;

    // Per-partition dedup: partition key (closed_on) must be included in unique index.
    sqlx::query(
        r#"CREATE UNIQUE INDEX IF NOT EXISTS ux_trade_rebate_k8s_ticket_service_closed
           ON trd.trade_rebate_k8s (ticket, trade_service_id, closed_on)"#,
    )
    .execute(pool)
    .await?;

    sqlx::query(
        r#"CREATE INDEX IF NOT EXISTS ix_trade_rebate_k8s_account_number
           ON trd.trade_rebate_k8s (account_number)"#,
    )
    .execute(pool)
    .await?;

    // FK: account_id → trd."_Account"("Id")
    sqlx::query(
        r#"DO $$ BEGIN
               ALTER TABLE trd.trade_rebate_k8s
               ADD CONSTRAINT fk_trade_rebate_k8s_account_id
               FOREIGN KEY (account_id) REFERENCES trd."_Account"("Id");
           EXCEPTION WHEN duplicate_object THEN NULL;
           END $$"#,
    )
    .execute(pool)
    .await?;

    // FK: trade_service_id → trd."_TradeService"("Id")
    sqlx::query(
        r#"DO $$ BEGIN
               ALTER TABLE trd.trade_rebate_k8s
               ADD CONSTRAINT fk_trade_rebate_k8s_trade_service_id
               FOREIGN KEY (trade_service_id) REFERENCES trd."_TradeService"("Id");
           EXCEPTION WHEN duplicate_object THEN NULL;
           END $$"#,
    )
    .execute(pool)
    .await?;

    // trd.rebate_k8s — partitioned by created_on
    sqlx::query(
        r#"CREATE TABLE IF NOT EXISTS trd.rebate_k8s (
            id              BIGINT        NOT NULL,
            party_id        BIGINT        NOT NULL,
            account_id      BIGINT        NOT NULL,
            fund_type       INT           NOT NULL DEFAULT 0,
            currency_id     INT           NOT NULL DEFAULT -1,
            amount          NUMERIC(20,8) NOT NULL DEFAULT 0,
            trade_rebate_id BIGINT,
            hold_until_on   TIMESTAMPTZ,
            information     TEXT          NOT NULL DEFAULT '',
            created_on      TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
            PRIMARY KEY (id, created_on)
        ) PARTITION BY RANGE (created_on)"#,
    )
    .execute(pool)
    .await?;

    // Migrate existing PascalCase columns to snake_case (idempotent)
    sqlx::query(
        r#"DO $$ BEGIN
               IF EXISTS (SELECT 1 FROM information_schema.columns
                          WHERE table_schema='trd' AND table_name='rebate_k8s' AND column_name='Id') THEN
                   ALTER TABLE trd.rebate_k8s RENAME COLUMN "Id" TO id;
               END IF;
               IF EXISTS (SELECT 1 FROM information_schema.columns
                          WHERE table_schema='trd' AND table_name='rebate_k8s' AND column_name='PartyId') THEN
                   ALTER TABLE trd.rebate_k8s RENAME COLUMN "PartyId" TO party_id;
               END IF;
               IF EXISTS (SELECT 1 FROM information_schema.columns
                          WHERE table_schema='trd' AND table_name='rebate_k8s' AND column_name='AccountId') THEN
                   ALTER TABLE trd.rebate_k8s RENAME COLUMN "AccountId" TO account_id;
               END IF;
               IF EXISTS (SELECT 1 FROM information_schema.columns
                          WHERE table_schema='trd' AND table_name='rebate_k8s' AND column_name='FundType') THEN
                   ALTER TABLE trd.rebate_k8s RENAME COLUMN "FundType" TO fund_type;
               END IF;
               IF EXISTS (SELECT 1 FROM information_schema.columns
                          WHERE table_schema='trd' AND table_name='rebate_k8s' AND column_name='CurrencyId') THEN
                   ALTER TABLE trd.rebate_k8s RENAME COLUMN "CurrencyId" TO currency_id;
               END IF;
               IF EXISTS (SELECT 1 FROM information_schema.columns
                          WHERE table_schema='trd' AND table_name='rebate_k8s' AND column_name='Amount') THEN
                   ALTER TABLE trd.rebate_k8s RENAME COLUMN "Amount" TO amount;
               END IF;
               IF EXISTS (SELECT 1 FROM information_schema.columns
                          WHERE table_schema='trd' AND table_name='rebate_k8s' AND column_name='TradeRebateId') THEN
                   ALTER TABLE trd.rebate_k8s RENAME COLUMN "TradeRebateId" TO trade_rebate_id;
               END IF;
               IF EXISTS (SELECT 1 FROM information_schema.columns
                          WHERE table_schema='trd' AND table_name='rebate_k8s' AND column_name='HoldUntilOn') THEN
                   ALTER TABLE trd.rebate_k8s RENAME COLUMN "HoldUntilOn" TO hold_until_on;
               END IF;
               IF EXISTS (SELECT 1 FROM information_schema.columns
                          WHERE table_schema='trd' AND table_name='rebate_k8s' AND column_name='Information') THEN
                   ALTER TABLE trd.rebate_k8s RENAME COLUMN "Information" TO information;
               END IF;
               IF EXISTS (SELECT 1 FROM information_schema.columns
                          WHERE table_schema='trd' AND table_name='rebate_k8s' AND column_name='CreatedOn') THEN
                   ALTER TABLE trd.rebate_k8s RENAME COLUMN "CreatedOn" TO created_on;
               END IF;
           END $$"#,
    )
    .execute(pool)
    .await?;

    sqlx::query(
        r#"CREATE INDEX IF NOT EXISTS ix_rebate_k8s_account_id
           ON trd.rebate_k8s (account_id)"#,
    )
    .execute(pool)
    .await?;

    sqlx::query(
        r#"CREATE INDEX IF NOT EXISTS ix_rebate_k8s_party_id
           ON trd.rebate_k8s (party_id)"#,
    )
    .execute(pool)
    .await?;

    sqlx::query(
        r#"CREATE INDEX IF NOT EXISTS ix_rebate_k8s_trade_rebate_id
           ON trd.rebate_k8s (trade_rebate_id)"#,
    )
    .execute(pool)
    .await?;

    // FK: account_id → trd."_Account"("Id")
    sqlx::query(
        r#"DO $$ BEGIN
               ALTER TABLE trd.rebate_k8s
               ADD CONSTRAINT fk_rebate_k8s_account_id
               FOREIGN KEY (account_id) REFERENCES trd."_Account"("Id");
           EXCEPTION WHEN duplicate_object THEN NULL;
           END $$"#,
    )
    .execute(pool)
    .await?;

    Ok(())
}

// ── Year sub-partition management ─────────────────────────────────────────────

/// Ensure the year sub-partition exists for a snake_case K8s parent table.
/// E.g. ensure_year_partition_snake(pool, "trd", "trade_rebate_k8s", 2026) creates
/// trd.trade_rebate_k8s_2026 FOR VALUES FROM ('2026-01-01') TO ('2027-01-01').
pub async fn ensure_year_partition_snake(
    pool: &PgPool,
    schema: &str,
    parent: &str,
    year: i32,
) -> Result<()> {
    let partition = format!("{schema}.{parent}_{year}");
    let parent_full = format!("{schema}.{parent}");
    let from = format!("{}-01-01", year);
    let to = format!("{}-01-01", year + 1);

    sqlx::query(&format!(
        r#"CREATE TABLE IF NOT EXISTS {partition}
           PARTITION OF {parent_full}
           FOR VALUES FROM ('{from}') TO ('{to}')"#
    ))
    .execute(pool)
    .await?;

    Ok(())
}
