use anyhow::Result;
use sqlx::PgPool;

// ── Parent table DDL ──────────────────────────────────────────────────────────

/// Create all K8s partitioned parent tables if they don't already exist.
/// Safe to call repeatedly — all DDL uses IF NOT EXISTS.
pub async fn ensure_parent_tables(pool: &PgPool) -> Result<()> {
    // core."_MatterK8s" — partitioned by PostedOn (immutable creation time)
    // Kept as quoted CamelCase to match the existing table created in the DB.
    sqlx::query(
        r#"CREATE TABLE IF NOT EXISTS core."_MatterK8s" (
            "Id"       BIGINT       NOT NULL,
            "Pid"      BIGINT,
            "Type"     INT          NOT NULL,
            "StateId"  INT          NOT NULL,
            "PostedOn" TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
            "StatedOn" TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
            PRIMARY KEY ("Id", "PostedOn")
        ) PARTITION BY RANGE ("PostedOn")"#,
    )
    .execute(pool)
    .await?;

    // Snowflake IDs are globally unique by construction; a regular index suffices.
    // PG partitioned tables cannot have UNIQUE indexes that exclude the partition key.
    sqlx::query(
        r#"CREATE INDEX IF NOT EXISTS "IX__MatterK8s_Id"
           ON core."_MatterK8s" ("Id")"#,
    )
    .execute(pool)
    .await?;

    sqlx::query(
        r#"CREATE INDEX IF NOT EXISTS "IX__MatterK8s_StateId"
           ON core."_MatterK8s" ("StateId")"#,
    )
    .execute(pool)
    .await?;

    sqlx::query(
        r#"CREATE INDEX IF NOT EXISTS "IX__MatterK8s_Type"
           ON core."_MatterK8s" ("Type")"#,
    )
    .execute(pool)
    .await?;

    // core.activity_k8s — partitioned by PerformedOn (immutable write time)
    // Scheduler-only table; mono continues using core."_Activity".
    sqlx::query(
        r#"CREATE TABLE IF NOT EXISTS core.activity_k8s (
            "Id"          BIGINT       GENERATED BY DEFAULT AS IDENTITY,
            "MatterId"    BIGINT       NOT NULL,
            "PartyId"     BIGINT       NOT NULL,
            "PerformedOn" TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
            "OnStateId"   INT          NOT NULL,
            "ActionId"    INT          NOT NULL DEFAULT 0,
            "ToStateId"   INT          NOT NULL,
            "Data"        TEXT         NOT NULL DEFAULT '',
            PRIMARY KEY ("Id", "PerformedOn")
        ) PARTITION BY RANGE ("PerformedOn")"#,
    )
    .execute(pool)
    .await?;

    sqlx::query(
        r#"CREATE INDEX IF NOT EXISTS ix_activity_k8s_matter_id
           ON core.activity_k8s ("MatterId")"#,
    )
    .execute(pool)
    .await?;

    sqlx::query(
        r#"CREATE INDEX IF NOT EXISTS ix_activity_k8s_party_id
           ON core.activity_k8s ("PartyId")"#,
    )
    .execute(pool)
    .await?;

    // acct.wallet_transaction_k8s — partitioned by CreatedOn (immutable insert time)
    // Scheduler-only table; mono continues using acct."_WalletTransaction".
    sqlx::query(
        r#"CREATE TABLE IF NOT EXISTS acct.wallet_transaction_k8s (
            "Id"          BIGINT       GENERATED BY DEFAULT AS IDENTITY,
            "WalletId"    BIGINT       NOT NULL,
            "InvoiceId"   BIGINT,
            "MatterId"    BIGINT       NOT NULL,
            "PrevBalance" BIGINT       NOT NULL DEFAULT 0,
            "Amount"      BIGINT       NOT NULL DEFAULT 0,
            "CreatedOn"   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
            "UpdatedOn"   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
            PRIMARY KEY ("Id", "CreatedOn")
        ) PARTITION BY RANGE ("CreatedOn")"#,
    )
    .execute(pool)
    .await?;

    sqlx::query(
        r#"CREATE INDEX IF NOT EXISTS ix_wallet_transaction_k8s_matter_id
           ON acct.wallet_transaction_k8s ("MatterId")"#,
    )
    .execute(pool)
    .await?;

    sqlx::query(
        r#"CREATE INDEX IF NOT EXISTS ix_wallet_transaction_k8s_wallet_id
           ON acct.wallet_transaction_k8s ("WalletId")"#,
    )
    .execute(pool)
    .await?;

    // FK: WalletId → acct."_Wallet"("Id")
    sqlx::query(
        r#"DO $$ BEGIN
               ALTER TABLE acct.wallet_transaction_k8s
               ADD CONSTRAINT fk_wallet_transaction_k8s_wallet_id
               FOREIGN KEY ("WalletId") REFERENCES acct."_Wallet"("Id");
           EXCEPTION WHEN duplicate_object THEN NULL;
           END $$"#,
    )
    .execute(pool)
    .await?;

    // FK: InvoiceId → acct."_Invoice"("Id") (nullable)
    sqlx::query(
        r#"DO $$ BEGIN
               ALTER TABLE acct.wallet_transaction_k8s
               ADD CONSTRAINT fk_wallet_transaction_k8s_invoice_id
               FOREIGN KEY ("InvoiceId") REFERENCES acct."_Invoice"("Id");
           EXCEPTION WHEN duplicate_object THEN NULL;
           END $$"#,
    )
    .execute(pool)
    .await?;

    // Backfill: add GENERATED BY DEFAULT AS IDENTITY to "Id" on existing trade_rebate_k8s tables.
    // Safe to call repeatedly — DO block skips if already an identity column.
    sqlx::query(
        r#"DO $$ BEGIN
               IF NOT EXISTS (
                   SELECT 1 FROM information_schema.columns
                   WHERE table_schema = 'trd' AND table_name = 'trade_rebate_k8s'
                     AND column_name = 'Id' AND is_identity = 'YES'
               ) THEN
                   ALTER TABLE trd.trade_rebate_k8s ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY;
               END IF;
           END $$"#,
    )
    .execute(pool)
    .await?;

    // trd.trade_rebate_k8s — partitioned by ClosedOn (trade close time, immutable)
    // Scheduler-only table; mono continues using trd."_TradeRebate".
    sqlx::query(
        r#"CREATE TABLE IF NOT EXISTS trd.trade_rebate_k8s (
            "Id"             BIGINT         NOT NULL,
            "AccountId"      BIGINT,
            "TradeServiceId" INT            NOT NULL,
            "Ticket"         BIGINT         NOT NULL,
            "AccountNumber"  BIGINT         NOT NULL,
            "CurrencyId"     INT            NOT NULL DEFAULT -1,
            "Volume"         INT            NOT NULL DEFAULT 0,
            "Status"         INT            NOT NULL DEFAULT 0,
            "RuleType"       INT            NOT NULL DEFAULT 199,
            "CreatedOn"      TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
            "UpdatedOn"      TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
            "ClosedOn"       TIMESTAMPTZ    NOT NULL,
            "OpenedOn"       TIMESTAMPTZ    NOT NULL,
            "TimeStamp"      BIGINT         NOT NULL DEFAULT 0,
            "Action"         INT            NOT NULL DEFAULT 0,
            "DealId"         BIGINT         NOT NULL DEFAULT 0,
            "Symbol"         VARCHAR(32)    NOT NULL DEFAULT '',
            "ReferPath"      VARCHAR(512)   NOT NULL DEFAULT '',
            "Commission"     NUMERIC(18,8)  NOT NULL DEFAULT 0,
            "Swaps"          NUMERIC(18,8)  NOT NULL DEFAULT 0,
            "OpenPrice"      NUMERIC(18,8)  NOT NULL DEFAULT 0,
            "ClosePrice"     NUMERIC(18,8)  NOT NULL DEFAULT 0,
            "Profit"         NUMERIC(18,8)  NOT NULL DEFAULT 0,
            "Reason"         INT            NOT NULL DEFAULT 0,
            PRIMARY KEY ("Id", "ClosedOn")
        ) PARTITION BY RANGE ("ClosedOn")"#,
    )
    .execute(pool)
    .await?;

    // Snowflake IDs are globally unique by construction; a regular index suffices.
    sqlx::query(
        r#"CREATE INDEX IF NOT EXISTS ix_trade_rebate_k8s_id
           ON trd.trade_rebate_k8s ("Id")"#,
    )
    .execute(pool)
    .await?;

    // Per-partition dedup: partition key (ClosedOn) must be included in unique index.
    sqlx::query(
        r#"CREATE UNIQUE INDEX IF NOT EXISTS ux_trade_rebate_k8s_ticket_service_closed
           ON trd.trade_rebate_k8s ("Ticket", "TradeServiceId", "ClosedOn")"#,
    )
    .execute(pool)
    .await?;

    sqlx::query(
        r#"CREATE INDEX IF NOT EXISTS ix_trade_rebate_k8s_account_number
           ON trd.trade_rebate_k8s ("AccountNumber")"#,
    )
    .execute(pool)
    .await?;

    // trd.rebate_k8s — partitioned by CreatedOn (insert time)
    // Replaces the application-level year tables trd."_Rebate_{year}".
    // Scheduler-only; mono continues using trd."_Rebate_{year}".
    sqlx::query(
        r#"CREATE TABLE IF NOT EXISTS trd.rebate_k8s (
            "Id"            BIGINT        NOT NULL,
            "PartyId"       BIGINT        NOT NULL,
            "AccountId"     BIGINT        NOT NULL,
            "FundType"      INT           NOT NULL DEFAULT 0,
            "CurrencyId"    INT           NOT NULL DEFAULT -1,
            "Amount"        NUMERIC(20,8) NOT NULL DEFAULT 0,
            "TradeRebateId" BIGINT,
            "HoldUntilOn"   TIMESTAMPTZ,
            "Information"   TEXT          NOT NULL DEFAULT '',
            "CreatedOn"     TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
            PRIMARY KEY ("Id", "CreatedOn")
        ) PARTITION BY RANGE ("CreatedOn")"#,
    )
    .execute(pool)
    .await?;

    sqlx::query(
        r#"CREATE INDEX IF NOT EXISTS ix_rebate_k8s_account_id
           ON trd.rebate_k8s ("AccountId")"#,
    )
    .execute(pool)
    .await?;

    sqlx::query(
        r#"CREATE INDEX IF NOT EXISTS ix_rebate_k8s_party_id
           ON trd.rebate_k8s ("PartyId")"#,
    )
    .execute(pool)
    .await?;

    sqlx::query(
        r#"CREATE INDEX IF NOT EXISTS ix_rebate_k8s_trade_rebate_id
           ON trd.rebate_k8s ("TradeRebateId")"#,
    )
    .execute(pool)
    .await?;

    // FK: AccountId → trd."_Account"("Id")
    sqlx::query(
        r#"DO $$ BEGIN
               ALTER TABLE trd.rebate_k8s
               ADD CONSTRAINT fk_rebate_k8s_account_id
               FOREIGN KEY ("AccountId") REFERENCES trd."_Account"("Id");
           EXCEPTION WHEN duplicate_object THEN NULL;
           END $$"#,
    )
    .execute(pool)
    .await?;

    Ok(())
}

// ── Year sub-partition management ─────────────────────────────────────────────

/// Ensure the year sub-partition exists for a quoted CamelCase K8s parent table.
/// E.g. ensure_year_partition(pool, "core", "_MatterK8s", 2026) creates
/// core."_MatterK8s_2026" FOR VALUES FROM ('2026-01-01') TO ('2027-01-01').
pub async fn ensure_year_partition(
    pool: &PgPool,
    schema: &str,
    parent: &str,
    year: i32,
) -> Result<()> {
    let partition = format!(r#"{schema}."{}_{year}""#, parent);
    let parent_full = format!(r#"{schema}."{parent}""#);
    let from = format!("{}-01-01", year);
    let to = format!("{}-01-01", year + 1);

    sqlx::query(&format!(
        r#"CREATE TABLE IF NOT EXISTS {partition}
           PARTITION OF {parent_full}
           FOR VALUES FROM ('{from}') TO ('{to}')"#
    ))
    .execute(pool)
    .await?;

    Ok(())
}

/// Ensure the year sub-partition exists for a snake_case K8s parent table.
/// E.g. ensure_year_partition_snake(pool, "trd", "trade_rebate_k8s", 2026) creates
/// trd.trade_rebate_k8s_2026 FOR VALUES FROM ('2026-01-01') TO ('2027-01-01').
pub async fn ensure_year_partition_snake(
    pool: &PgPool,
    schema: &str,
    parent: &str,
    year: i32,
) -> Result<()> {
    let partition = format!("{schema}.{parent}_{year}");
    let parent_full = format!("{schema}.{parent}");
    let from = format!("{}-01-01", year);
    let to = format!("{}-01-01", year + 1);

    sqlx::query(&format!(
        r#"CREATE TABLE IF NOT EXISTS {partition}
           PARTITION OF {parent_full}
           FOR VALUES FROM ('{from}') TO ('{to}')"#
    ))
    .execute(pool)
    .await?;

    Ok(())
}
