// <auto-generated />
using System;
using Bacera.Gateway.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bacera.Gateway.Infrastructure.Data.Migrations.TenantDb
{
    [DbContext(typeof(TenantDbContext))]
    [Migration("20250626120000_RenameTradeIdToTicketInEventShopRewardRebate")]
    partial class RenameTradeIdToTicketInEventShopRewardRebate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            // EventShopRewardRebate entity after the migration (with Ticket column)
            modelBuilder.Entity("Bacera.Gateway.EventShopRewardRebate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("Amount")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("EventShopRewardId")
                        .HasColumnType("bigint");

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.Property<long>("Ticket")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("_EventShopRewardRebate_pkey");

                    b.HasIndex(new[] { "EventShopRewardId" }, "IX__EventShopRewardRebate_EventShopRewardId");

                    b.HasIndex(new[] { "Status" }, "IX__EventShopRewardRebate_Status");

                    b.HasIndex(new[] { "Ticket" }, "IX__EventShopRewardRebate_TradeId");

                    b.ToTable("_EventShopRewardRebate", "event");
                });

            // EventShopReward entity (referenced by foreign key)
            modelBuilder.Entity("Bacera.Gateway.EventShopReward", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("EffectiveTo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("EventPartyId")
                        .HasColumnType("bigint");

                    b.Property<long>("EventShopItemId")
                        .HasColumnType("bigint");

                    b.Property<long>("OperatorPartyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("1");

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.Property<long>("TotalPoint")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("_EventShopReward_pkey");

                    b.HasIndex("OperatorPartyId");

                    b.HasIndex(new[] { "EventPartyId" }, "IX__EventShopReward_EventPartyId");

                    b.HasIndex(new[] { "EventShopItemId" }, "IX__EventShopReward_EventShopItemId");

                    b.HasIndex(new[] { "Status" }, "IX__EventShopReward_Status");

                    b.ToTable("_EventShopReward", "event");
                });

            // Add foreign key relationship
            modelBuilder.Entity("Bacera.Gateway.EventShopRewardRebate", b =>
                {
                    b.HasOne("Bacera.Gateway.EventShopReward", "EventShopReward")
                        .WithMany("EventShopRewardRebates")
                        .HasForeignKey("EventShopRewardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventShopReward");
                });

            modelBuilder.Entity("Bacera.Gateway.EventShopReward", b =>
                {
                    b.Navigation("EventShopRewardRebates");
                });

#pragma warning restore 612, 618
        }
    }
} 